// JLPT N5 + N4 Kanji Database
// Each entry: { kanji, level, meanings, onyomi, kunyomi, examples }

const KANJI_DATA = [
    // ── JLPT N5 ──────────────────────────────────────────────
    { kanji: "一", level: "N5", meanings: ["one"], onyomi: ["イチ", "イツ"], kunyomi: ["ひと-", "ひとつ"], examples: ["一つ (ひとつ) one thing", "一月 (いちがつ) January"] },
    { kanji: "二", level: "N5", meanings: ["two"], onyomi: ["ニ"], kunyomi: ["ふた-", "ふたつ"], examples: ["二つ (ふたつ) two things", "二月 (にがつ) February"] },
    { kanji: "三", level: "N5", meanings: ["three"], onyomi: ["サン"], kunyomi: ["み-", "みっつ"], examples: ["三つ (みっつ) three things", "三月 (さんがつ) March"] },
    { kanji: "四", level: "N5", meanings: ["four"], onyomi: ["シ"], kunyomi: ["よ-", "よっつ", "よん"], examples: ["四つ (よっつ) four things", "四月 (しがつ) April"] },
    { kanji: "五", level: "N5", meanings: ["five"], onyomi: ["ゴ"], kunyomi: ["いつ-", "いつつ"], examples: ["五つ (いつつ) five things", "五月 (ごがつ) May"] },
    { kanji: "六", level: "N5", meanings: ["six"], onyomi: ["ロク"], kunyomi: ["む-", "むっつ", "むい"], examples: ["六つ (むっつ) six things", "六月 (ろくがつ) June"] },
    { kanji: "七", level: "N5", meanings: ["seven"], onyomi: ["シチ"], kunyomi: ["なな-", "ななつ", "なの"], examples: ["七つ (ななつ) seven things", "七月 (しちがつ) July"] },
    { kanji: "八", level: "N5", meanings: ["eight"], onyomi: ["ハチ"], kunyomi: ["や-", "やっつ", "よう"], examples: ["八つ (やっつ) eight things", "八月 (はちがつ) August"] },
    { kanji: "九", level: "N5", meanings: ["nine"], onyomi: ["キュウ", "ク"], kunyomi: ["ここの-", "ここのつ"], examples: ["九つ (ここのつ) nine things", "九月 (くがつ) September"] },
    { kanji: "十", level: "N5", meanings: ["ten"], onyomi: ["ジュウ", "ジッ"], kunyomi: ["とお", "と"], examples: ["十 (じゅう) ten", "十月 (じゅうがつ) October"] },
    { kanji: "百", level: "N5", meanings: ["hundred"], onyomi: ["ヒャク"], kunyomi: [], examples: ["百円 (ひゃくえん) 100 yen", "三百 (さんびゃく) 300"] },
    { kanji: "千", level: "N5", meanings: ["thousand"], onyomi: ["セン"], kunyomi: ["ち"], examples: ["千円 (せんえん) 1000 yen", "三千 (さんぜん) 3000"] },
    { kanji: "万", level: "N5", meanings: ["ten thousand"], onyomi: ["マン", "バン"], kunyomi: [], examples: ["一万 (いちまん) 10,000", "万円 (まんえん) 10,000 yen"] },
    { kanji: "円", level: "N5", meanings: ["yen", "circle", "round"], onyomi: ["エン"], kunyomi: ["まる-い"], examples: ["百円 (ひゃくえん) 100 yen", "円い (まるい) round"] },
    { kanji: "年", level: "N5", meanings: ["year"], onyomi: ["ネン"], kunyomi: ["とし"], examples: ["今年 (ことし) this year", "来年 (らいねん) next year"] },
    { kanji: "月", level: "N5", meanings: ["month", "moon"], onyomi: ["ゲツ", "ガツ"], kunyomi: ["つき"], examples: ["今月 (こんげつ) this month", "月曜日 (げつようび) Monday"] },
    { kanji: "日", level: "N5", meanings: ["day", "sun", "Japan"], onyomi: ["ニチ", "ジツ"], kunyomi: ["ひ", "か"], examples: ["毎日 (まいにち) every day", "日本 (にほん) Japan"] },
    { kanji: "火", level: "N5", meanings: ["fire"], onyomi: ["カ"], kunyomi: ["ひ", "ほ-"], examples: ["火曜日 (かようび) Tuesday", "火事 (かじ) fire/blaze"] },
    { kanji: "水", level: "N5", meanings: ["water"], onyomi: ["スイ"], kunyomi: ["みず"], examples: ["水曜日 (すいようび) Wednesday", "水 (みず) water"] },
    { kanji: "木", level: "N5", meanings: ["tree", "wood"], onyomi: ["モク", "ボク"], kunyomi: ["き", "こ-"], examples: ["木曜日 (もくようび) Thursday", "木 (き) tree"] },
    { kanji: "金", level: "N5", meanings: ["gold", "money", "Friday"], onyomi: ["キン", "コン"], kunyomi: ["かね", "かな-"], examples: ["金曜日 (きんようび) Friday", "お金 (おかね) money"] },
    { kanji: "土", level: "N5", meanings: ["earth", "soil", "Saturday"], onyomi: ["ド", "ト"], kunyomi: ["つち"], examples: ["土曜日 (どようび) Saturday", "土 (つち) soil"] },
    { kanji: "山", level: "N5", meanings: ["mountain"], onyomi: ["サン"], kunyomi: ["やま"], examples: ["富士山 (ふじさん) Mt. Fuji", "山 (やま) mountain"] },
    { kanji: "川", level: "N5", meanings: ["river"], onyomi: ["セン"], kunyomi: ["かわ"], examples: ["川 (かわ) river", "小川 (おがわ) stream"] },
    { kanji: "田", level: "N5", meanings: ["rice field"], onyomi: ["デン"], kunyomi: ["た"], examples: ["田んぼ (たんぼ) rice paddy", "田中 (たなか) Tanaka (surname)"] },
    { kanji: "人", level: "N5", meanings: ["person"], onyomi: ["ジン", "ニン"], kunyomi: ["ひと"], examples: ["日本人 (にほんじん) Japanese person", "人 (ひと) person"] },
    { kanji: "口", level: "N5", meanings: ["mouth"], onyomi: ["コウ", "ク"], kunyomi: ["くち"], examples: ["口 (くち) mouth", "人口 (じんこう) population"] },
    { kanji: "目", level: "N5", meanings: ["eye"], onyomi: ["モク", "ボク"], kunyomi: ["め", "ま-"], examples: ["目 (め) eye", "目的 (もくてき) purpose"] },
    { kanji: "耳", level: "N5", meanings: ["ear"], onyomi: ["ジ"], kunyomi: ["みみ"], examples: ["耳 (みみ) ear", "耳鼻科 (じびか) ENT clinic"] },
    { kanji: "手", level: "N5", meanings: ["hand"], onyomi: ["シュ"], kunyomi: ["て", "た-"], examples: ["手 (て) hand", "上手 (じょうず) skillful"] },
    { kanji: "足", level: "N5", meanings: ["foot", "leg", "enough"], onyomi: ["ソク"], kunyomi: ["あし", "た-りる"], examples: ["足 (あし) foot/leg", "足りる (たりる) to be enough"] },
    { kanji: "力", level: "N5", meanings: ["power", "strength"], onyomi: ["リョク", "リキ"], kunyomi: ["ちから"], examples: ["力 (ちから) strength", "電力 (でんりょく) electric power"] },
    { kanji: "女", level: "N5", meanings: ["woman", "female"], onyomi: ["ジョ", "ニョ"], kunyomi: ["おんな", "め-"], examples: ["女 (おんな) woman", "女性 (じょせい) female"] },
    { kanji: "男", level: "N5", meanings: ["man", "male"], onyomi: ["ダン", "ナン"], kunyomi: ["おとこ"], examples: ["男 (おとこ) man", "男性 (だんせい) male"] },
    { kanji: "子", level: "N5", meanings: ["child"], onyomi: ["シ", "ス"], kunyomi: ["こ", "ね"], examples: ["子供 (こども) child", "子 (こ) child"] },
    { kanji: "父", level: "N5", meanings: ["father"], onyomi: ["フ"], kunyomi: ["ちち"], examples: ["父 (ちち) (my) father", "お父さん (おとうさん) father"] },
    { kanji: "母", level: "N5", meanings: ["mother"], onyomi: ["ボ"], kunyomi: ["はは"], examples: ["母 (はは) (my) mother", "お母さん (おかあさん) mother"] },
    { kanji: "先", level: "N5", meanings: ["previous", "ahead", "tip"], onyomi: ["セン"], kunyomi: ["さき", "ま-ず"], examples: ["先生 (せんせい) teacher", "先 (さき) ahead"] },
    { kanji: "生", level: "N5", meanings: ["life", "birth"], onyomi: ["セイ", "ショウ"], kunyomi: ["い-きる", "う-まれる", "なま"], examples: ["先生 (せんせい) teacher", "学生 (がくせい) student"] },
    { kanji: "学", level: "N5", meanings: ["study", "learning"], onyomi: ["ガク"], kunyomi: ["まな-ぶ"], examples: ["学校 (がっこう) school", "学生 (がくせい) student"] },
    { kanji: "校", level: "N5", meanings: ["school"], onyomi: ["コウ"], kunyomi: [], examples: ["学校 (がっこう) school", "高校 (こうこう) high school"] },
    { kanji: "大", level: "N5", meanings: ["big", "large"], onyomi: ["ダイ", "タイ"], kunyomi: ["おお-きい", "おお-"], examples: ["大きい (おおきい) big", "大学 (だいがく) university"] },
    { kanji: "小", level: "N5", meanings: ["small", "little"], onyomi: ["ショウ"], kunyomi: ["ちい-さい", "こ-", "お-"], examples: ["小さい (ちいさい) small", "小学校 (しょうがっこう) elementary school"] },
    { kanji: "中", level: "N5", meanings: ["middle", "inside", "China"], onyomi: ["チュウ"], kunyomi: ["なか"], examples: ["中 (なか) inside", "中学校 (ちゅうがっこう) middle school"] },
    { kanji: "上", level: "N5", meanings: ["up", "above", "on top"], onyomi: ["ジョウ", "ショウ"], kunyomi: ["うえ", "うわ-", "かみ", "あ-げる", "のぼ-る"], examples: ["上 (うえ) above", "上手 (じょうず) skillful"] },
    { kanji: "下", level: "N5", meanings: ["down", "below", "under"], onyomi: ["カ", "ゲ"], kunyomi: ["した", "しも", "もと", "さ-げる", "くだ-る", "お-りる"], examples: ["下 (した) below", "地下 (ちか) underground"] },
    { kanji: "左", level: "N5", meanings: ["left"], onyomi: ["サ"], kunyomi: ["ひだり"], examples: ["左 (ひだり) left", "左右 (さゆう) left and right"] },
    { kanji: "右", level: "N5", meanings: ["right"], onyomi: ["ウ", "ユウ"], kunyomi: ["みぎ"], examples: ["右 (みぎ) right", "右折 (うせつ) right turn"] },
    { kanji: "前", level: "N5", meanings: ["front", "before"], onyomi: ["ゼン"], kunyomi: ["まえ"], examples: ["前 (まえ) front/before", "名前 (なまえ) name"] },
    { kanji: "後", level: "N5", meanings: ["behind", "after"], onyomi: ["ゴ", "コウ"], kunyomi: ["うし-ろ", "のち", "あと", "おく-れる"], examples: ["後 (あと) after", "午後 (ごご) afternoon"] },
    { kanji: "東", level: "N5", meanings: ["east"], onyomi: ["トウ"], kunyomi: ["ひがし"], examples: ["東 (ひがし) east", "東京 (とうきょう) Tokyo"] },
    { kanji: "西", level: "N5", meanings: ["west"], onyomi: ["セイ", "サイ"], kunyomi: ["にし"], examples: ["西 (にし) west", "西洋 (せいよう) the West"] },
    { kanji: "南", level: "N5", meanings: ["south"], onyomi: ["ナン", "ナ"], kunyomi: ["みなみ"], examples: ["南 (みなみ) south", "南米 (なんべい) South America"] },
    { kanji: "北", level: "N5", meanings: ["north"], onyomi: ["ホク"], kunyomi: ["きた"], examples: ["北 (きた) north", "北海道 (ほっかいどう) Hokkaido"] },
    { kanji: "外", level: "N5", meanings: ["outside", "foreign"], onyomi: ["ガイ", "ゲ"], kunyomi: ["そと", "ほか", "はず-れる"], examples: ["外 (そと) outside", "外国 (がいこく) foreign country"] },
    { kanji: "門", level: "N5", meanings: ["gate"], onyomi: ["モン"], kunyomi: ["かど"], examples: ["門 (もん) gate", "専門 (せんもん) specialty"] },
    { kanji: "入", level: "N5", meanings: ["enter", "put in"], onyomi: ["ニュウ"], kunyomi: ["い-る", "い-れる", "はい-る"], examples: ["入る (はいる) to enter", "入口 (いりぐち) entrance"] },
    { kanji: "出", level: "N5", meanings: ["exit", "come out"], onyomi: ["シュツ", "スイ"], kunyomi: ["で-る", "だ-す"], examples: ["出る (でる) to exit", "出口 (でぐち) exit"] },
    { kanji: "本", level: "N5", meanings: ["book", "origin", "Japan"], onyomi: ["ホン"], kunyomi: ["もと"], examples: ["本 (ほん) book", "日本 (にほん) Japan"] },
    { kanji: "何", level: "N5", meanings: ["what"], onyomi: ["カ"], kunyomi: ["なに", "なん"], examples: ["何 (なに) what", "何時 (なんじ) what time"] },
    { kanji: "国", level: "N5", meanings: ["country", "nation"], onyomi: ["コク"], kunyomi: ["くに"], examples: ["国 (くに) country", "外国 (がいこく) foreign country"] },
    { kanji: "語", level: "N5", meanings: ["language", "word"], onyomi: ["ゴ"], kunyomi: ["かた-る"], examples: ["日本語 (にほんご) Japanese", "英語 (えいご) English"] },
    { kanji: "字", level: "N5", meanings: ["character", "letter"], onyomi: ["ジ"], kunyomi: ["あざ"], examples: ["漢字 (かんじ) kanji", "字 (じ) character"] },
    { kanji: "文", level: "N5", meanings: ["sentence", "writing"], onyomi: ["ブン", "モン"], kunyomi: ["ふみ"], examples: ["文 (ぶん) sentence", "文化 (ぶんか) culture"] },
    { kanji: "書", level: "N5", meanings: ["write"], onyomi: ["ショ"], kunyomi: ["か-く"], examples: ["書く (かく) to write", "書類 (しょるい) documents"] },
    { kanji: "読", level: "N5", meanings: ["read"], onyomi: ["ドク", "トク", "トウ"], kunyomi: ["よ-む"], examples: ["読む (よむ) to read", "読書 (どくしょ) reading"] },
    { kanji: "話", level: "N5", meanings: ["talk", "story"], onyomi: ["ワ"], kunyomi: ["はな-す", "はなし"], examples: ["話す (はなす) to talk", "電話 (でんわ) telephone"] },
    { kanji: "聞", level: "N5", meanings: ["hear", "listen", "ask"], onyomi: ["ブン", "モン"], kunyomi: ["き-く", "き-こえる"], examples: ["聞く (きく) to hear/ask", "新聞 (しんぶん) newspaper"] },
    { kanji: "言", level: "N5", meanings: ["say", "word"], onyomi: ["ゲン", "ゴン"], kunyomi: ["い-う", "こと"], examples: ["言う (いう) to say", "言葉 (ことば) word/language"] },
    { kanji: "見", level: "N5", meanings: ["see", "look", "watch"], onyomi: ["ケン"], kunyomi: ["み-る", "み-せる", "み-える"], examples: ["見る (みる) to see", "見せる (みせる) to show"] },
    { kanji: "食", level: "N5", meanings: ["eat", "food"], onyomi: ["ショク", "ジキ"], kunyomi: ["た-べる", "く-う"], examples: ["食べる (たべる) to eat", "食事 (しょくじ) meal"] },
    { kanji: "飲", level: "N5", meanings: ["drink"], onyomi: ["イン"], kunyomi: ["の-む"], examples: ["飲む (のむ) to drink", "飲み物 (のみもの) drink/beverage"] },
    { kanji: "買", level: "N5", meanings: ["buy"], onyomi: ["バイ"], kunyomi: ["か-う"], examples: ["買う (かう) to buy", "買い物 (かいもの) shopping"] },
    { kanji: "来", level: "N5", meanings: ["come"], onyomi: ["ライ"], kunyomi: ["く-る", "き-", "こ-"], examples: ["来る (くる) to come", "来年 (らいねん) next year"] },
    { kanji: "行", level: "N5", meanings: ["go", "conduct"], onyomi: ["コウ", "ギョウ", "アン"], kunyomi: ["い-く", "ゆ-く", "おこな-う"], examples: ["行く (いく) to go", "旅行 (りょこう) travel"] },
    { kanji: "帰", level: "N5", meanings: ["return", "go back"], onyomi: ["キ"], kunyomi: ["かえ-る", "かえ-す"], examples: ["帰る (かえる) to return home", "帰国 (きこく) return to one's country"] },
    { kanji: "立", level: "N5", meanings: ["stand"], onyomi: ["リツ", "リュウ"], kunyomi: ["た-つ", "た-てる"], examples: ["立つ (たつ) to stand", "立場 (たちば) position/standpoint"] },
    { kanji: "休", level: "N5", meanings: ["rest", "holiday"], onyomi: ["キュウ"], kunyomi: ["やす-む", "やす-み", "やす-める"], examples: ["休む (やすむ) to rest", "休日 (きゅうじつ) holiday"] },
    { kanji: "会", level: "N5", meanings: ["meet", "meeting", "association"], onyomi: ["カイ", "エ"], kunyomi: ["あ-う"], examples: ["会う (あう) to meet", "会社 (かいしゃ) company"] },
    { kanji: "分", level: "N5", meanings: ["minute", "part", "understand"], onyomi: ["ブン", "フン", "ブ"], kunyomi: ["わ-かる", "わ-ける"], examples: ["三十分 (さんじゅっぷん) 30 minutes", "分かる (わかる) to understand"] },
    { kanji: "半", level: "N5", meanings: ["half"], onyomi: ["ハン"], kunyomi: ["なか-ば"], examples: ["半分 (はんぶん) half", "一時半 (いちじはん) 1:30"] },
    { kanji: "天", level: "N5", meanings: ["sky", "heaven"], onyomi: ["テン"], kunyomi: ["あめ", "あま-"], examples: ["天気 (てんき) weather", "天国 (てんごく) heaven"] },
    { kanji: "気", level: "N5", meanings: ["spirit", "feeling", "atmosphere"], onyomi: ["キ", "ケ"], kunyomi: [], examples: ["天気 (てんき) weather", "気分 (きぶん) feeling"] },
    { kanji: "電", level: "N5", meanings: ["electricity"], onyomi: ["デン"], kunyomi: [], examples: ["電話 (でんわ) telephone", "電車 (でんしゃ) train"] },
    { kanji: "車", level: "N5", meanings: ["car", "vehicle"], onyomi: ["シャ"], kunyomi: ["くるま"], examples: ["車 (くるま) car", "電車 (でんしゃ) train"] },
    { kanji: "道", level: "N5", meanings: ["road", "way", "path"], onyomi: ["ドウ", "トウ"], kunyomi: ["みち"], examples: ["道 (みち) road", "北海道 (ほっかいどう) Hokkaido"] },
    { kanji: "時", level: "N5", meanings: ["time", "hour", "o'clock"], onyomi: ["ジ"], kunyomi: ["とき"], examples: ["三時 (さんじ) 3 o'clock", "時間 (じかん) time"] },
    { kanji: "間", level: "N5", meanings: ["interval", "between"], onyomi: ["カン", "ケン"], kunyomi: ["あいだ", "ま"], examples: ["時間 (じかん) time", "人間 (にんげん) human being"] },
    { kanji: "長", level: "N5", meanings: ["long", "leader"], onyomi: ["チョウ"], kunyomi: ["なが-い", "おさ"], examples: ["長い (ながい) long", "社長 (しゃちょう) company president"] },
    { kanji: "白", level: "N5", meanings: ["white"], onyomi: ["ハク", "ビャク"], kunyomi: ["しろ", "しろ-い", "しら-"], examples: ["白い (しろい) white", "白黒 (しろくろ) black and white"] },
    { kanji: "黒", level: "N5", meanings: ["black"], onyomi: ["コク"], kunyomi: ["くろ", "くろ-い"], examples: ["黒い (くろい) black", "黒板 (こくばん) blackboard"] },
    { kanji: "赤", level: "N5", meanings: ["red"], onyomi: ["セキ", "シャク"], kunyomi: ["あか", "あか-い", "あか-らめる"], examples: ["赤い (あかい) red", "赤ちゃん (あかちゃん) baby"] },
    { kanji: "青", level: "N5", meanings: ["blue", "green"], onyomi: ["セイ", "ショウ"], kunyomi: ["あお", "あお-い"], examples: ["青い (あおい) blue", "青春 (せいしゅん) youth"] },
    { kanji: "高", level: "N5", meanings: ["tall", "expensive", "high"], onyomi: ["コウ"], kunyomi: ["たか-い", "たか-まる", "たか-める"], examples: ["高い (たかい) tall/expensive", "高校 (こうこう) high school"] },
    { kanji: "新", level: "N5", meanings: ["new"], onyomi: ["シン"], kunyomi: ["あたら-しい", "あら-", "にい-"], examples: ["新しい (あたらしい) new", "新聞 (しんぶん) newspaper"] },
    { kanji: "古", level: "N5", meanings: ["old (things)"], onyomi: ["コ"], kunyomi: ["ふる-い", "ふる-す"], examples: ["古い (ふるい) old", "中古 (ちゅうこ) used/secondhand"] },
    { kanji: "好", level: "N5", meanings: ["like", "fond of"], onyomi: ["コウ"], kunyomi: ["す-く", "この-む", "よ-い"], examples: ["好き (すき) like/fond of", "好む (このむ) to prefer"] },
    { kanji: "名", level: "N5", meanings: ["name", "famous"], onyomi: ["メイ", "ミョウ"], kunyomi: ["な"], examples: ["名前 (なまえ) name", "名刺 (めいし) business card"] },
    { kanji: "今", level: "N5", meanings: ["now", "present"], onyomi: ["コン", "キン"], kunyomi: ["いま"], examples: ["今 (いま) now", "今日 (きょう) today"] },
    { kanji: "毎", level: "N5", meanings: ["every", "each"], onyomi: ["マイ"], kunyomi: [], examples: ["毎日 (まいにち) every day", "毎年 (まいとし) every year"] },
    { kanji: "明", level: "N5", meanings: ["bright", "clear", "next"], onyomi: ["メイ", "ミョウ"], kunyomi: ["あか-るい", "あか-るむ", "あ-ける", "あき-らか"], examples: ["明るい (あかるい) bright", "明日 (あした) tomorrow"] },
    { kanji: "朝", level: "N5", meanings: ["morning"], onyomi: ["チョウ"], kunyomi: ["あさ"], examples: ["今朝 (けさ) this morning", "朝食 (ちょうしょく) breakfast"] },
    { kanji: "昼", level: "N5", meanings: ["noon", "daytime"], onyomi: ["チュウ"], kunyomi: ["ひる"], examples: ["昼 (ひる) noon", "昼食 (ちゅうしょく) lunch"] },
    { kanji: "夜", level: "N5", meanings: ["night", "evening"], onyomi: ["ヤ"], kunyomi: ["よ", "よる"], examples: ["今夜 (こんや) tonight", "夜 (よる) night"] },
    { kanji: "週", level: "N5", meanings: ["week"], onyomi: ["シュウ"], kunyomi: [], examples: ["今週 (こんしゅう) this week", "来週 (らいしゅう) next week"] },
    { kanji: "曜", level: "N5", meanings: ["day of week"], onyomi: ["ヨウ"], kunyomi: [], examples: ["月曜日 (げつようび) Monday", "何曜日 (なんようび) what day of week"] },
    { kanji: "友", level: "N5", meanings: ["friend"], onyomi: ["ユウ"], kunyomi: ["とも"], examples: ["友達 (ともだち) friend", "友人 (ゆうじん) friend"] },
    { kanji: "家", level: "N5", meanings: ["house", "home", "family"], onyomi: ["カ", "ケ"], kunyomi: ["いえ", "や"], examples: ["家 (いえ) house", "家族 (かぞく) family"] },
    { kanji: "花", level: "N5", meanings: ["flower"], onyomi: ["カ"], kunyomi: ["はな"], examples: ["花 (はな) flower", "花見 (はなみ) cherry blossom viewing"] },
    { kanji: "雨", level: "N5", meanings: ["rain"], onyomi: ["ウ"], kunyomi: ["あめ", "あま-"], examples: ["雨 (あめ) rain", "雨天 (うてん) rainy weather"] },
    { kanji: "空", level: "N5", meanings: ["sky", "empty"], onyomi: ["クウ"], kunyomi: ["そら", "あ-く", "から", "す-く"], examples: ["空 (そら) sky", "空港 (くうこう) airport"] },
    { kanji: "海", level: "N5", meanings: ["sea", "ocean"], onyomi: ["カイ"], kunyomi: ["うみ"], examples: ["海 (うみ) sea", "海外 (かいがい) overseas"] },
    { kanji: "店", level: "N5", meanings: ["shop", "store"], onyomi: ["テン"], kunyomi: ["みせ"], examples: ["お店 (おみせ) shop", "書店 (しょてん) bookstore"] },
    { kanji: "駅", level: "N5", meanings: ["train station"], onyomi: ["エキ"], kunyomi: [], examples: ["駅 (えき) station", "駅前 (えきまえ) in front of station"] },
    { kanji: "社", level: "N5", meanings: ["company", "shrine"], onyomi: ["シャ"], kunyomi: ["やしろ"], examples: ["会社 (かいしゃ) company", "社長 (しゃちょう) company president"] },
    { kanji: "所", level: "N5", meanings: ["place"], onyomi: ["ショ"], kunyomi: ["ところ", "どこ-"], examples: ["場所 (ばしょ) place", "所 (ところ) place"] },
    { kanji: "近", level: "N5", meanings: ["near", "close"], onyomi: ["キン"], kunyomi: ["ちか-い", "ちか-づく"], examples: ["近い (ちかい) near", "近所 (きんじょ) neighborhood"] },
    { kanji: "遠", level: "N5", meanings: ["far", "distant"], onyomi: ["エン", "オン"], kunyomi: ["とお-い", "とお-ざかる"], examples: ["遠い (とおい) far", "遠足 (えんそく) excursion"] },

    // ── JLPT N4 ──────────────────────────────────────────────
    { kanji: "悪", level: "N4", meanings: ["bad", "evil"], onyomi: ["アク", "オ"], kunyomi: ["わる-い", "わる-"], examples: ["悪い (わるい) bad", "悪口 (わるくち) bad-mouthing"] },
    { kanji: "安", level: "N4", meanings: ["cheap", "relax", "safe"], onyomi: ["アン"], kunyomi: ["やす-い", "やす-らか"], examples: ["安い (やすい) cheap", "安全 (あんぜん) safe"] },
    { kanji: "暗", level: "N4", meanings: ["dark"], onyomi: ["アン"], kunyomi: ["くら-い", "くら-む"], examples: ["暗い (くらい) dark", "暗記 (あんき) memorization"] },
    { kanji: "医", level: "N4", meanings: ["medicine", "doctor"], onyomi: ["イ"], kunyomi: [], examples: ["医者 (いしゃ) doctor", "医学 (いがく) medicine"] },
    { kanji: "意", level: "N4", meanings: ["intention", "meaning"], onyomi: ["イ"], kunyomi: [], examples: ["意味 (いみ) meaning", "注意 (ちゅうい) attention/caution"] },
    { kanji: "育", level: "N4", meanings: ["raise", "grow up"], onyomi: ["イク"], kunyomi: ["そだ-てる", "そだ-つ", "はぐく-む"], examples: ["教育 (きょういく) education", "育てる (そだてる) to raise"] },
    { kanji: "員", level: "N4", meanings: ["member", "staff"], onyomi: ["イン"], kunyomi: [], examples: ["社員 (しゃいん) company employee", "店員 (てんいん) store clerk"] },
    { kanji: "院", level: "N4", meanings: ["institution", "temple"], onyomi: ["イン"], kunyomi: [], examples: ["病院 (びょういん) hospital", "大学院 (だいがくいん) graduate school"] },
    { kanji: "運", level: "N4", meanings: ["carry", "luck"], onyomi: ["ウン"], kunyomi: ["はこ-ぶ"], examples: ["運動 (うんどう) exercise", "運転 (うんてん) driving"] },
    { kanji: "映", level: "N4", meanings: ["reflect", "project"], onyomi: ["エイ"], kunyomi: ["うつ-る", "うつ-す", "は-える"], examples: ["映画 (えいが) movie", "映る (うつる) to be reflected"] },
    { kanji: "英", level: "N4", meanings: ["England", "hero"], onyomi: ["エイ"], kunyomi: [], examples: ["英語 (えいご) English", "英国 (えいこく) England"] },
    { kanji: "音", level: "N4", meanings: ["sound", "noise"], onyomi: ["オン", "イン"], kunyomi: ["おと", "ね"], examples: ["音楽 (おんがく) music", "音 (おと) sound"] },
    { kanji: "歌", level: "N4", meanings: ["song", "sing"], onyomi: ["カ"], kunyomi: ["うた", "うた-う"], examples: ["歌 (うた) song", "歌手 (かしゅ) singer"] },
    { kanji: "科", level: "N4", meanings: ["department", "subject"], onyomi: ["カ"], kunyomi: [], examples: ["科学 (かがく) science", "科目 (かもく) subject"] },
    { kanji: "夏", level: "N4", meanings: ["summer"], onyomi: ["カ", "ゲ"], kunyomi: ["なつ"], examples: ["夏 (なつ) summer", "夏休み (なつやすみ) summer vacation"] },
    { kanji: "開", level: "N4", meanings: ["open"], onyomi: ["カイ"], kunyomi: ["あ-ける", "あ-く", "ひら-く", "ひら-ける"], examples: ["開ける (あける) to open", "開発 (かいはつ) development"] },
    { kanji: "漢", level: "N4", meanings: ["China", "Chinese character"], onyomi: ["カン"], kunyomi: [], examples: ["漢字 (かんじ) kanji", "漢方 (かんぽう) Chinese herbal medicine"] },
    { kanji: "起", level: "N4", meanings: ["wake up", "rise", "occur"], onyomi: ["キ"], kunyomi: ["お-きる", "お-こる", "お-こす"], examples: ["起きる (おきる) to wake up", "起こる (おこる) to occur"] },
    { kanji: "期", level: "N4", meanings: ["period", "time", "term"], onyomi: ["キ", "ゴ"], kunyomi: [], examples: ["期待 (きたい) expectation", "学期 (がっき) school term"] },
    { kanji: "急", level: "N4", meanings: ["hurry", "sudden"], onyomi: ["キュウ"], kunyomi: ["いそ-ぐ", "きゅう-に"], examples: ["急ぐ (いそぐ) to hurry", "急に (きゅうに) suddenly"] },
    { kanji: "牛", level: "N4", meanings: ["cow", "beef"], onyomi: ["ギュウ"], kunyomi: ["うし"], examples: ["牛 (うし) cow", "牛乳 (ぎゅうにゅう) milk"] },
    { kanji: "去", level: "N4", meanings: ["past", "leave"], onyomi: ["キョ", "コ"], kunyomi: ["さ-る", "す-ぎる"], examples: ["去年 (きょねん) last year", "過去 (かこ) the past"] },
    { kanji: "魚", level: "N4", meanings: ["fish"], onyomi: ["ギョ"], kunyomi: ["さかな", "うお"], examples: ["魚 (さかな) fish", "金魚 (きんぎょ) goldfish"] },
    { kanji: "強", level: "N4", meanings: ["strong"], onyomi: ["キョウ", "ゴウ"], kunyomi: ["つよ-い", "つよ-まる", "し-いる"], examples: ["強い (つよい) strong", "勉強 (べんきょう) study"] },
    { kanji: "教", level: "N4", meanings: ["teach", "religion"], onyomi: ["キョウ"], kunyomi: ["おし-える", "おそ-わる"], examples: ["教える (おしえる) to teach", "教育 (きょういく) education"] },
    { kanji: "兄", level: "N4", meanings: ["older brother"], onyomi: ["ケイ", "キョウ"], kunyomi: ["あに"], examples: ["兄 (あに) older brother", "兄弟 (きょうだい) siblings"] },
    { kanji: "形", level: "N4", meanings: ["form", "shape"], onyomi: ["ケイ", "ギョウ"], kunyomi: ["かた", "かたち"], examples: ["形 (かたち) shape", "人形 (にんぎょう) doll"] },
    { kanji: "計", level: "N4", meanings: ["measure", "plan", "total"], onyomi: ["ケイ"], kunyomi: ["はか-る"], examples: ["時計 (とけい) clock/watch", "計画 (けいかく) plan"] },
    { kanji: "研", level: "N4", meanings: ["research", "polish"], onyomi: ["ケン"], kunyomi: ["と-ぐ"], examples: ["研究 (けんきゅう) research", "研究者 (けんきゅうしゃ) researcher"] },
    { kanji: "険", level: "N4", meanings: ["steep", "risky"], onyomi: ["ケン"], kunyomi: ["けわ-しい"], examples: ["危険 (きけん) danger", "保険 (ほけん) insurance"] },
    { kanji: "元", level: "N4", meanings: ["origin", "former", "healthy"], onyomi: ["ゲン", "ガン"], kunyomi: ["もと"], examples: ["元気 (げんき) healthy/lively", "元 (もと) origin/former"] },
    { kanji: "工", level: "N4", meanings: ["construction", "craft"], onyomi: ["コウ", "ク"], kunyomi: [], examples: ["工場 (こうじょう) factory", "工事 (こうじ) construction"] },
    { kanji: "考", level: "N4", meanings: ["think", "consider"], onyomi: ["コウ"], kunyomi: ["かんが-える"], examples: ["考える (かんがえる) to think", "考え (かんがえ) idea/thought"] },
    { kanji: "合", level: "N4", meanings: ["combine", "fit", "suit"], onyomi: ["ゴウ", "ガッ", "カッ"], kunyomi: ["あ-う", "あ-わせる", "あ-わす"], examples: ["合う (あう) to fit", "試合 (しあい) match/game"] },
    { kanji: "黒", level: "N4", meanings: ["black"], onyomi: ["コク"], kunyomi: ["くろ", "くろ-い"], examples: ["黒い (くろい) black", "黒板 (こくばん) blackboard"] },
    { kanji: "若", level: "N4", meanings: ["young"], onyomi: ["ジャク", "ニャク"], kunyomi: ["わか-い", "も-しくは"], examples: ["若い (わかい) young", "若者 (わかもの) young person"] },
    { kanji: "作", level: "N4", meanings: ["make", "create"], onyomi: ["サク", "サ"], kunyomi: ["つく-る"], examples: ["作る (つくる) to make", "作品 (さくひん) work/piece"] },
    { kanji: "思", level: "N4", meanings: ["think", "feel"], onyomi: ["シ"], kunyomi: ["おも-う"], examples: ["思う (おもう) to think/feel", "思い出 (おもいで) memory"] },
    { kanji: "止", level: "N4", meanings: ["stop"], onyomi: ["シ"], kunyomi: ["と-まる", "と-める", "や-む", "や-める"], examples: ["止まる (とまる) to stop", "止める (とめる) to stop something"] },
    { kanji: "紙", level: "N4", meanings: ["paper"], onyomi: ["シ"], kunyomi: ["かみ"], examples: ["紙 (かみ) paper", "手紙 (てがみ) letter"] },
    { kanji: "事", level: "N4", meanings: ["thing", "matter", "fact"], onyomi: ["ジ", "ズ"], kunyomi: ["こと"], examples: ["事 (こと) thing/matter", "仕事 (しごと) work/job"] },
    { kanji: "自", level: "N4", meanings: ["self", "oneself"], onyomi: ["ジ", "シ"], kunyomi: ["みずか-ら"], examples: ["自分 (じぶん) oneself", "自動車 (じどうしゃ) automobile"] },
    { kanji: "室", level: "N4", meanings: ["room"], onyomi: ["シツ"], kunyomi: ["むろ"], examples: ["教室 (きょうしつ) classroom", "洋室 (ようしつ) Western-style room"] },
    { kanji: "質", level: "N4", meanings: ["quality", "nature"], onyomi: ["シツ", "シチ", "チ"], kunyomi: ["たち"], examples: ["質問 (しつもん) question", "品質 (ひんしつ) quality"] },
    { kanji: "主", level: "N4", meanings: ["master", "main", "lord"], onyomi: ["シュ", "ス"], kunyomi: ["ぬし", "おも-"], examples: ["主人 (しゅじん) husband/master", "主な (おもな) main"] },
    { kanji: "集", level: "N4", meanings: ["gather", "collect"], onyomi: ["シュウ"], kunyomi: ["あつ-まる", "あつ-める", "つど-う"], examples: ["集まる (あつまる) to gather", "集める (あつめる) to collect"] },
    { kanji: "習", level: "N4", meanings: ["learn", "practice"], onyomi: ["シュウ"], kunyomi: ["なら-う"], examples: ["習う (ならう) to learn", "練習 (れんしゅう) practice"] },
    { kanji: "重", level: "N4", meanings: ["heavy", "important"], onyomi: ["ジュウ", "チョウ"], kunyomi: ["おも-い", "かさ-なる", "かさ-ねる", "え-"], examples: ["重い (おもい) heavy", "重要 (じゅうよう) important"] },
    { kanji: "春", level: "N4", meanings: ["spring"], onyomi: ["シュン"], kunyomi: ["はる"], examples: ["春 (はる) spring", "青春 (せいしゅん) youth"] },
    { kanji: "書", level: "N4", meanings: ["write"], onyomi: ["ショ"], kunyomi: ["か-く"], examples: ["書く (かく) to write", "教科書 (きょうかしょ) textbook"] },
    { kanji: "色", level: "N4", meanings: ["color"], onyomi: ["ショク", "シキ"], kunyomi: ["いろ"], examples: ["色 (いろ) color", "茶色 (ちゃいろ) brown"] },
    { kanji: "森", level: "N4", meanings: ["forest"], onyomi: ["シン"], kunyomi: ["もり"], examples: ["森 (もり) forest", "森林 (しんりん) forest/woods"] },
    { kanji: "親", level: "N4", meanings: ["parent", "intimate"], onyomi: ["シン"], kunyomi: ["おや", "した-しい", "した-しむ"], examples: ["親 (おや) parent", "親切 (しんせつ) kind"] },
    { kanji: "数", level: "N4", meanings: ["number", "count"], onyomi: ["スウ", "ス", "サク"], kunyomi: ["かず", "かぞ-える"], examples: ["数 (かず) number", "数学 (すうがく) mathematics"] },
    { kanji: "正", level: "N4", meanings: ["correct", "proper"], onyomi: ["セイ", "ショウ"], kunyomi: ["ただ-しい", "ただ-す", "まさ"], examples: ["正しい (ただしい) correct", "正月 (しょうがつ) New Year"] },
    { kanji: "声", level: "N4", meanings: ["voice", "sound"], onyomi: ["セイ", "ショウ"], kunyomi: ["こえ", "こわ-"], examples: ["声 (こえ) voice", "声優 (せいゆう) voice actor"] },
    { kanji: "切", level: "N4", meanings: ["cut", "important"], onyomi: ["セツ", "サイ"], kunyomi: ["き-る", "き-れる"], examples: ["切る (きる) to cut", "大切 (たいせつ) important"] },
    { kanji: "雪", level: "N4", meanings: ["snow"], onyomi: ["セツ"], kunyomi: ["ゆき"], examples: ["雪 (ゆき) snow", "雪国 (ゆきぐに) snowy country"] },
    { kanji: "線", level: "N4", meanings: ["line"], onyomi: ["セン"], kunyomi: [], examples: ["線 (せん) line", "新幹線 (しんかんせん) bullet train"] },
    { kanji: "走", level: "N4", meanings: ["run"], onyomi: ["ソウ"], kunyomi: ["はし-る"], examples: ["走る (はしる) to run", "競走 (きょうそう) race"] },
    { kanji: "送", level: "N4", meanings: ["send", "see off"], onyomi: ["ソウ"], kunyomi: ["おく-る"], examples: ["送る (おくる) to send", "放送 (ほうそう) broadcast"] },
    { kanji: "待", level: "N4", meanings: ["wait"], onyomi: ["タイ"], kunyomi: ["ま-つ"], examples: ["待つ (まつ) to wait", "待合室 (まちあいしつ) waiting room"] },
    { kanji: "貸", level: "N4", meanings: ["lend", "rent out"], onyomi: ["タイ"], kunyomi: ["か-す"], examples: ["貸す (かす) to lend", "貸し出し (かしだし) lending"] },
    { kanji: "代", level: "N4", meanings: ["substitute", "era", "fee"], onyomi: ["ダイ", "タイ"], kunyomi: ["か-わる", "か-える", "よ", "しろ"], examples: ["時代 (じだい) era", "代わる (かわる) to substitute"] },
    { kanji: "台", level: "N4", meanings: ["rack", "stand", "counter"], onyomi: ["ダイ", "タイ"], kunyomi: [], examples: ["台所 (だいどころ) kitchen", "舞台 (ぶたい) stage"] },
    { kanji: "体", level: "N4", meanings: ["body"], onyomi: ["タイ", "テイ"], kunyomi: ["からだ"], examples: ["体 (からだ) body", "体育 (たいいく) physical education"] },
    { kanji: "地", level: "N4", meanings: ["ground", "earth"], onyomi: ["チ", "ジ"], kunyomi: [], examples: ["地図 (ちず) map", "地下鉄 (ちかてつ) subway"] },
    { kanji: "池", level: "N4", meanings: ["pond"], onyomi: ["チ"], kunyomi: ["いけ"], examples: ["池 (いけ) pond", "電池 (でんち) battery"] },
    { kanji: "注", level: "N4", meanings: ["pour", "focus", "note"], onyomi: ["チュウ"], kunyomi: ["そそ-ぐ"], examples: ["注意 (ちゅうい) attention", "注文 (ちゅうもん) order (food)"] },
    { kanji: "昼", level: "N4", meanings: ["noon"], onyomi: ["チュウ"], kunyomi: ["ひる"], examples: ["昼 (ひる) noon", "昼食 (ちゅうしょく) lunch"] },
    { kanji: "鳥", level: "N4", meanings: ["bird"], onyomi: ["チョウ"], kunyomi: ["とり"], examples: ["鳥 (とり) bird", "野鳥 (やちょう) wild bird"] },
    { kanji: "通", level: "N4", meanings: ["pass through", "commute"], onyomi: ["ツウ", "ツ"], kunyomi: ["とお-る", "とお-す", "かよ-う"], examples: ["通る (とおる) to pass", "交通 (こうつう) traffic"] },
    { kanji: "低", level: "N4", meanings: ["low"], onyomi: ["テイ"], kunyomi: ["ひく-い", "ひく-まる", "ひく-める"], examples: ["低い (ひくい) low", "低下 (ていか) decline"] },
    { kanji: "点", level: "N4", meanings: ["point", "dot", "score"], onyomi: ["テン"], kunyomi: ["てん"], examples: ["点数 (てんすう) score", "起点 (きてん) starting point"] },
    { kanji: "電", level: "N4", meanings: ["electricity"], onyomi: ["デン"], kunyomi: [], examples: ["電話 (でんわ) telephone", "電気 (でんき) electricity"] },
    { kanji: "転", level: "N4", meanings: ["roll", "turn", "change"], onyomi: ["テン"], kunyomi: ["ころ-がる", "ころ-げる", "ころ-がす", "うた-る", "まわ-る"], examples: ["運転 (うんてん) driving", "転ぶ (ころぶ) to fall down"] },
    { kanji: "度", level: "N4", meanings: ["degree", "times", "occasion"], onyomi: ["ド", "ト", "タク"], kunyomi: ["たび"], examples: ["今度 (こんど) next time", "一度 (いちど) once"] },
    { kanji: "冬", level: "N4", meanings: ["winter"], onyomi: ["トウ"], kunyomi: ["ふゆ"], examples: ["冬 (ふゆ) winter", "冬休み (ふゆやすみ) winter vacation"] },
    { kanji: "動", level: "N4", meanings: ["move"], onyomi: ["ドウ"], kunyomi: ["うご-く", "うご-かす"], examples: ["動く (うごく) to move", "運動 (うんどう) exercise"] },
    { kanji: "肉", level: "N4", meanings: ["meat", "flesh"], onyomi: ["ニク"], kunyomi: [], examples: ["肉 (にく) meat", "牛肉 (ぎゅうにく) beef"] },
    { kanji: "荷", level: "N4", meanings: ["luggage", "cargo"], onyomi: ["カ"], kunyomi: ["に"], examples: ["荷物 (にもつ) luggage", "荷 (に) load"] },
    { kanji: "発", level: "N4", meanings: ["depart", "emit", "start"], onyomi: ["ハツ", "ホツ"], kunyomi: [], examples: ["出発 (しゅっぱつ) departure", "発見 (はっけん) discovery"] },
    { kanji: "反", level: "N4", meanings: ["anti", "return", "counter"], onyomi: ["ハン", "ホン", "タン"], kunyomi: ["そ-る", "そ-らす", "かえ-す"], examples: ["反対 (はんたい) opposition", "反省 (はんせい) reflection"] },
    { kanji: "番", level: "N4", meanings: ["number", "turn", "watch"], onyomi: ["バン"], kunyomi: [], examples: ["番号 (ばんごう) number", "一番 (いちばん) number one/most"] },
    { kanji: "病", level: "N4", meanings: ["illness", "disease"], onyomi: ["ビョウ", "ヘイ"], kunyomi: ["やまい", "や-む"], examples: ["病気 (びょうき) illness", "病院 (びょういん) hospital"] },
    { kanji: "品", level: "N4", meanings: ["goods", "item", "quality"], onyomi: ["ヒン", "ホン"], kunyomi: ["しな"], examples: ["品物 (しなもの) goods", "商品 (しょうひん) product"] },
    { kanji: "服", level: "N4", meanings: ["clothing", "obey"], onyomi: ["フク"], kunyomi: [], examples: ["服 (ふく) clothes", "洋服 (ようふく) Western clothing"] },
    { kanji: "物", level: "N4", meanings: ["thing", "object"], onyomi: ["ブツ", "モツ"], kunyomi: ["もの", "もの-"], examples: ["物 (もの) thing", "食べ物 (たべもの) food"] },
    { kanji: "歩", level: "N4", meanings: ["walk", "step"], onyomi: ["ホ", "ブ", "フ"], kunyomi: ["ある-く", "あゆ-む"], examples: ["歩く (あるく) to walk", "散歩 (さんぽ) walk/stroll"] },
    { kanji: "方", level: "N4", meanings: ["direction", "person", "way"], onyomi: ["ホウ"], kunyomi: ["かた"], examples: ["方向 (ほうこう) direction", "あの方 (あのかた) that person"] },
    { kanji: "毎", level: "N4", meanings: ["every"], onyomi: ["マイ"], kunyomi: [], examples: ["毎日 (まいにち) every day", "毎年 (まいとし) every year"] },
    { kanji: "味", level: "N4", meanings: ["taste", "flavor"], onyomi: ["ミ"], kunyomi: ["あじ", "あじ-わう"], examples: ["味 (あじ) taste", "意味 (いみ) meaning"] },
    { kanji: "鳴", level: "N4", meanings: ["ring", "chirp", "sound"], onyomi: ["メイ"], kunyomi: ["な-く", "な-る", "な-らす"], examples: ["鳴る (なる) to ring", "鳴く (なく) to chirp/cry (animal)"] },
    { kanji: "問", level: "N4", meanings: ["question", "problem"], onyomi: ["モン"], kunyomi: ["と-う", "と-い", "とい"], examples: ["問題 (もんだい) problem", "質問 (しつもん) question"] },
    { kanji: "野", level: "N4", meanings: ["field", "plains"], onyomi: ["ヤ"], kunyomi: ["の"], examples: ["野原 (のはら) field", "野菜 (やさい) vegetables"] },
    { kanji: "有", level: "N4", meanings: ["exist", "have"], onyomi: ["ユウ", "ウ"], kunyomi: ["あ-る"], examples: ["有名 (ゆうめい) famous", "有る (ある) to exist/have"] },
    { kanji: "理", level: "N4", meanings: ["reason", "logic"], onyomi: ["リ"], kunyomi: ["ことわ-る"], examples: ["料理 (りょうり) cooking", "理由 (りゆう) reason"] },
    { kanji: "旅", level: "N4", meanings: ["travel", "trip"], onyomi: ["リョ"], kunyomi: ["たび"], examples: ["旅行 (りょこう) travel", "旅 (たび) journey"] },
    { kanji: "料", level: "N4", meanings: ["fee", "material"], onyomi: ["リョウ"], kunyomi: [], examples: ["料理 (りょうり) cooking", "料金 (りょうきん) fee/charge"] },
    { kanji: "林", level: "N4", meanings: ["forest", "grove"], onyomi: ["リン"], kunyomi: ["はやし"], examples: ["林 (はやし) forest/woods", "林業 (りんぎょう) forestry"] },
    { kanji: "留", level: "N4", meanings: ["stay", "keep"], onyomi: ["リュウ", "ル"], kunyomi: ["と-まる", "と-める"], examples: ["留学 (りゅうがく) study abroad", "留守 (るす) absence from home"] },
    { kanji: "例", level: "N4", meanings: ["example", "custom"], onyomi: ["レイ"], kunyomi: ["たと-える"], examples: ["例えば (たとえば) for example", "例 (れい) example"] },
    { kanji: "練", level: "N4", meanings: ["practice", "knead"], onyomi: ["レン"], kunyomi: ["ね-る"], examples: ["練習 (れんしゅう) practice", "訓練 (くんれん) training"] },
    { kanji: "曲", level: "N4", meanings: ["musical piece", "bend"], onyomi: ["キョク"], kunyomi: ["ま-がる", "ま-げる"], examples: ["曲 (きょく) melody/piece", "曲がる (まがる) to bend/turn"] },
    { kanji: "広", level: "N4", meanings: ["wide", "broad"], onyomi: ["コウ"], kunyomi: ["ひろ-い", "ひろ-める", "ひろ-がる", "ひろ-げる"], examples: ["広い (ひろい) wide/spacious", "広告 (こうこく) advertisement"] },
    { kanji: "光", level: "N4", meanings: ["light"], onyomi: ["コウ"], kunyomi: ["ひかり", "ひか-る"], examples: ["光 (ひかり) light", "観光 (かんこう) sightseeing"] },
    { kanji: "交", level: "N4", meanings: ["mix", "mingle", "exchange"], onyomi: ["コウ"], kunyomi: ["ま-じる", "ま-ざる", "ま-ぜる", "か-う", "か-わす"], examples: ["交通 (こうつう) traffic", "交換 (こうかん) exchange"] },
    { kanji: "弟", level: "N4", meanings: ["younger brother"], onyomi: ["テイ", "ダイ", "デ"], kunyomi: ["おとうと"], examples: ["弟 (おとうと) younger brother", "兄弟 (きょうだい) siblings"] },
    { kanji: "妹", level: "N4", meanings: ["younger sister"], onyomi: ["マイ"], kunyomi: ["いもうと"], examples: ["妹 (いもうと) younger sister", "姉妹 (しまい) sisters"] },
    { kanji: "姉", level: "N4", meanings: ["older sister"], onyomi: ["シ"], kunyomi: ["あね"], examples: ["姉 (あね) older sister", "お姉さん (おねえさん) older sister"] },
    { kanji: "特", level: "N4", meanings: ["special"], onyomi: ["トク"], kunyomi: [], examples: ["特別 (とくべつ) special", "特に (とくに) especially"] },
    { kanji: "族", level: "N4", meanings: ["tribe", "family"], onyomi: ["ゾク"], kunyomi: [], examples: ["家族 (かぞく) family", "民族 (みんぞく) ethnic group"] },
    { kanji: "太", level: "N4", meanings: ["fat", "thick"], onyomi: ["タイ", "タ"], kunyomi: ["ふと-い", "ふと-る"], examples: ["太い (ふとい) thick/fat", "太る (ふとる) to gain weight"] },
    { kanji: "細", level: "N4", meanings: ["thin", "fine", "detail"], onyomi: ["サイ"], kunyomi: ["ほそ-い", "ほそ-る", "こま-かい", "こま-か"], examples: ["細い (ほそい) thin", "細かい (こまかい) fine/detailed"] },
    { kanji: "星", level: "N4", meanings: ["star"], onyomi: ["セイ", "ショウ"], kunyomi: ["ほし"], examples: ["星 (ほし) star", "流れ星 (ながれぼし) shooting star"] },
    { kanji: "晴", level: "N4", meanings: ["clear up", "sunny"], onyomi: ["セイ"], kunyomi: ["は-れる", "は-らす"], examples: ["晴れる (はれる) to clear up", "晴天 (せいてん) clear weather"] },
    { kanji: "組", level: "N4", meanings: ["group", "class", "assemble"], onyomi: ["ソ"], kunyomi: ["く-む", "くみ"], examples: ["組 (くみ) group/class", "番組 (ばんぐみ) TV program"] },
    { kanji: "歳", level: "N4", meanings: ["age", "years old"], onyomi: ["サイ", "セイ"], kunyomi: [], examples: ["二十歳 (はたち) 20 years old", "お歳暮 (おせいぼ) year-end gift"] },
    { kanji: "座", level: "N4", meanings: ["sit", "seat"], onyomi: ["ザ"], kunyomi: ["すわ-る"], examples: ["座る (すわる) to sit", "座席 (ざせき) seat"] },
    { kanji: "市", level: "N4", meanings: ["city", "market"], onyomi: ["シ"], kunyomi: ["いち"], examples: ["市 (し) city", "市場 (いちば) market"] },
    { kanji: "社", level: "N4", meanings: ["company", "society", "shrine"], onyomi: ["シャ"], kunyomi: ["やしろ"], examples: ["会社 (かいしゃ) company", "社会 (しゃかい) society"] },
    { kanji: "弱", level: "N4", meanings: ["weak"], onyomi: ["ジャク"], kunyomi: ["よわ-い", "よわ-まる", "よわ-める", "よわ-る"], examples: ["弱い (よわい) weak", "弱点 (じゃくてん) weak point"] },
    { kanji: "借", level: "N4", meanings: ["borrow", "rent"], onyomi: ["シャク"], kunyomi: ["か-りる"], examples: ["借りる (かりる) to borrow", "借金 (しゃっきん) debt"] },
    { kanji: "写", level: "N4", meanings: ["copy", "photograph"], onyomi: ["シャ"], kunyomi: ["うつ-す", "うつ-る"], examples: ["写真 (しゃしん) photograph", "写す (うつす) to copy"] },
    { kanji: "登", level: "N4", meanings: ["climb", "register"], onyomi: ["トウ", "ト"], kunyomi: ["のぼ-る"], examples: ["登る (のぼる) to climb", "登山 (とざん) mountain climbing"] },
    { kanji: "洗", level: "N4", meanings: ["wash"], onyomi: ["セン"], kunyomi: ["あら-う"], examples: ["洗う (あらう) to wash", "洗濯 (せんたく) laundry"] },
    { kanji: "早", level: "N4", meanings: ["early", "fast"], onyomi: ["ソウ", "サッ"], kunyomi: ["はや-い", "はや-める", "はや-まる", "さっ-そく"], examples: ["早い (はやい) early/fast", "早起き (はやおき) early rising"] },
    { kanji: "速", level: "N4", meanings: ["fast", "speed"], onyomi: ["ソク"], kunyomi: ["はや-い", "はや-める", "はや-まる", "すみ-やか"], examples: ["速い (はやい) fast", "速度 (そくど) speed"] },
    { kanji: "知", level: "N4", meanings: ["know"], onyomi: ["チ"], kunyomi: ["し-る", "し-らせる"], examples: ["知る (しる) to know", "知識 (ちしき) knowledge"] },
    { kanji: "着", level: "N4", meanings: ["arrive", "wear"], onyomi: ["チャク", "ジャク"], kunyomi: ["き-る", "き-せる", "つ-く", "つ-ける"], examples: ["着る (きる) to wear", "到着 (とうちゃく) arrival"] },
    { kanji: "昔", level: "N4", meanings: ["old times", "past"], onyomi: ["セキ", "シャク"], kunyomi: ["むかし"], examples: ["昔 (むかし) old times", "昔話 (むかしばなし) old tale"] },
    { kanji: "以", level: "N4", meanings: ["by means of", "compared with"], onyomi: ["イ"], kunyomi: [], examples: ["以上 (いじょう) above/more than", "以下 (いか) below/less than"] },
    { kanji: "活", level: "N4", meanings: ["lively", "activity"], onyomi: ["カツ"], kunyomi: [], examples: ["活動 (かつどう) activity", "生活 (せいかつ) life/living"] },
    { kanji: "同", level: "N4", meanings: ["same", "agree"], onyomi: ["ドウ"], kunyomi: ["おな-じ"], examples: ["同じ (おなじ) same", "同意 (どうい) agreement"] },
    { kanji: "世", level: "N4", meanings: ["world", "generation"], onyomi: ["セイ", "セ"], kunyomi: ["よ"], examples: ["世界 (せかい) world", "世の中 (よのなか) the world/society"] },
    { kanji: "界", level: "N4", meanings: ["world", "boundary"], onyomi: ["カイ"], kunyomi: [], examples: ["世界 (せかい) world", "業界 (ぎょうかい) industry"] },
    { kanji: "次", level: "N4", meanings: ["next", "order"], onyomi: ["ジ", "シ"], kunyomi: ["つぎ", "つ-ぐ"], examples: ["次 (つぎ) next", "次第 (しだい) circumstance"] },
    { kanji: "使", level: "N4", meanings: ["use", "employ"], onyomi: ["シ"], kunyomi: ["つか-う"], examples: ["使う (つかう) to use", "大使 (たいし) ambassador"] },
    { kanji: "始", level: "N4", meanings: ["begin", "start"], onyomi: ["シ"], kunyomi: ["はじ-める", "はじ-まる"], examples: ["始める (はじめる) to begin", "始まる (はじまる) to start"] },
    { kanji: "終", level: "N4", meanings: ["end", "finish"], onyomi: ["シュウ"], kunyomi: ["お-わる", "お-える"], examples: ["終わる (おわる) to end", "終電 (しゅうでん) last train"] },
    { kanji: "乗", level: "N4", meanings: ["ride", "board"], onyomi: ["ジョウ"], kunyomi: ["の-る", "の-せる"], examples: ["乗る (のる) to ride", "乗り換え (のりかえ) transfer"] },
    { kanji: "返", level: "N4", meanings: ["return", "reply"], onyomi: ["ヘン"], kunyomi: ["かえ-す", "かえ-る"], examples: ["返す (かえす) to return", "返事 (へんじ) reply"] },
    { kanji: "忘", level: "N4", meanings: ["forget"], onyomi: ["ボウ"], kunyomi: ["わす-れる"], examples: ["忘れる (わすれる) to forget", "忘年会 (ぼうねんかい) year-end party"] },
    { kanji: "急", level: "N4", meanings: ["hurry", "sudden"], onyomi: ["キュウ"], kunyomi: ["いそ-ぐ"], examples: ["急ぐ (いそぐ) to hurry", "急に (きゅうに) suddenly"] },
    { kanji: "押", level: "N4", meanings: ["push", "stamp"], onyomi: ["オウ"], kunyomi: ["お-す", "お-さえる"], examples: ["押す (おす) to push", "押さえる (おさえる) to hold down"] },
    { kanji: "引", level: "N4", meanings: ["pull", "attract", "consult"], onyomi: ["イン"], kunyomi: ["ひ-く", "ひ-ける"], examples: ["引く (ひく) to pull", "引越し (ひっこし) moving house"] },
    { kanji: "英", level: "N4", meanings: ["English", "excellent"], onyomi: ["エイ"], kunyomi: ["はなぶさ"], examples: ["英語 (えいご) English language", "英国 (えいこく) England"] },
];

// Remove duplicate entries (same kanji)
const seen = new Set();
const KANJI = KANJI_DATA.filter(k => {
    if (seen.has(k.kanji)) return false;
    seen.add(k.kanji);
    return true;
});
