// Japanese Elementary School Kanji Database
// Each entry: { kanji, level, meanings, onyomi, kunyomi, examples }

const KANJI_DATA = [

    // ── 小1 (Grade 1 — 80 kanji) ────────────────────────────────
    { kanji: "一", level: "小1", meanings: ["one"], onyomi: ["イチ", "イツ"], kunyomi: ["ひと-", "ひとつ"], examples: ["一つ (ひとつ) one thing", "一月 (いちがつ) January"] },
    { kanji: "二", level: "小1", meanings: ["two"], onyomi: ["ニ"], kunyomi: ["ふた-", "ふたつ"], examples: ["二つ (ふたつ) two things", "二月 (にがつ) February"] },
    { kanji: "三", level: "小1", meanings: ["three"], onyomi: ["サン"], kunyomi: ["み-", "みっつ"], examples: ["三つ (みっつ) three things", "三月 (さんがつ) March"] },
    { kanji: "四", level: "小1", meanings: ["four"], onyomi: ["シ"], kunyomi: ["よ-", "よっつ", "よん"], examples: ["四つ (よっつ) four things", "四月 (しがつ) April"] },
    { kanji: "五", level: "小1", meanings: ["five"], onyomi: ["ゴ"], kunyomi: ["いつ-", "いつつ"], examples: ["五つ (いつつ) five things", "五月 (ごがつ) May"] },
    { kanji: "六", level: "小1", meanings: ["six"], onyomi: ["ロク"], kunyomi: ["む-", "むっつ", "むい"], examples: ["六つ (むっつ) six things", "六月 (ろくがつ) June"] },
    { kanji: "七", level: "小1", meanings: ["seven"], onyomi: ["シチ"], kunyomi: ["なな-", "ななつ", "なの"], examples: ["七つ (ななつ) seven things", "七月 (しちがつ) July"] },
    { kanji: "八", level: "小1", meanings: ["eight"], onyomi: ["ハチ"], kunyomi: ["や-", "やっつ", "よう"], examples: ["八つ (やっつ) eight things", "八月 (はちがつ) August"] },
    { kanji: "九", level: "小1", meanings: ["nine"], onyomi: ["キュウ", "ク"], kunyomi: ["ここの-", "ここのつ"], examples: ["九つ (ここのつ) nine things", "九月 (くがつ) September"] },
    { kanji: "十", level: "小1", meanings: ["ten"], onyomi: ["ジュウ", "ジッ"], kunyomi: ["とお", "と"], examples: ["十 (じゅう) ten", "十月 (じゅうがつ) October"] },
    { kanji: "百", level: "小1", meanings: ["hundred"], onyomi: ["ヒャク"], kunyomi: [], examples: ["百円 (ひゃくえん) 100 yen", "三百 (さんびゃく) 300"] },
    { kanji: "千", level: "小1", meanings: ["thousand"], onyomi: ["セン"], kunyomi: ["ち"], examples: ["千円 (せんえん) 1000 yen", "三千 (さんぜん) 3000"] },
    { kanji: "円", level: "小1", meanings: ["yen", "circle", "round"], onyomi: ["エン"], kunyomi: ["まる-い"], examples: ["百円 (ひゃくえん) 100 yen", "円い (まるい) round"] },
    { kanji: "年", level: "小1", meanings: ["year"], onyomi: ["ネン"], kunyomi: ["とし"], examples: ["今年 (ことし) this year", "来年 (らいねん) next year"] },
    { kanji: "月", level: "小1", meanings: ["month", "moon"], onyomi: ["ゲツ", "ガツ"], kunyomi: ["つき"], examples: ["今月 (こんげつ) this month", "月曜日 (げつようび) Monday"] },
    { kanji: "日", level: "小1", meanings: ["day", "sun", "Japan"], onyomi: ["ニチ", "ジツ"], kunyomi: ["ひ", "か"], examples: ["毎日 (まいにち) every day", "日本 (にほん) Japan"] },
    { kanji: "火", level: "小1", meanings: ["fire"], onyomi: ["カ"], kunyomi: ["ひ", "ほ-"], examples: ["火曜日 (かようび) Tuesday", "火事 (かじ) fire/blaze"] },
    { kanji: "水", level: "小1", meanings: ["water"], onyomi: ["スイ"], kunyomi: ["みず"], examples: ["水曜日 (すいようび) Wednesday", "水 (みず) water"] },
    { kanji: "木", level: "小1", meanings: ["tree", "wood"], onyomi: ["モク", "ボク"], kunyomi: ["き", "こ-"], examples: ["木曜日 (もくようび) Thursday", "木 (き) tree"] },
    { kanji: "金", level: "小1", meanings: ["gold", "money"], onyomi: ["キン", "コン"], kunyomi: ["かね", "かな-"], examples: ["金曜日 (きんようび) Friday", "お金 (おかね) money"] },
    { kanji: "土", level: "小1", meanings: ["earth", "soil"], onyomi: ["ド", "ト"], kunyomi: ["つち"], examples: ["土曜日 (どようび) Saturday", "土 (つち) soil"] },
    { kanji: "山", level: "小1", meanings: ["mountain"], onyomi: ["サン"], kunyomi: ["やま"], examples: ["富士山 (ふじさん) Mt. Fuji", "山 (やま) mountain"] },
    { kanji: "川", level: "小1", meanings: ["river"], onyomi: ["セン"], kunyomi: ["かわ"], examples: ["川 (かわ) river", "小川 (おがわ) stream"] },
    { kanji: "田", level: "小1", meanings: ["rice field"], onyomi: ["デン"], kunyomi: ["た"], examples: ["田んぼ (たんぼ) rice paddy", "田中 (たなか) Tanaka (surname)"] },
    { kanji: "人", level: "小1", meanings: ["person"], onyomi: ["ジン", "ニン"], kunyomi: ["ひと"], examples: ["日本人 (にほんじん) Japanese person", "人 (ひと) person"] },
    { kanji: "口", level: "小1", meanings: ["mouth"], onyomi: ["コウ", "ク"], kunyomi: ["くち"], examples: ["口 (くち) mouth", "人口 (じんこう) population"] },
    { kanji: "目", level: "小1", meanings: ["eye"], onyomi: ["モク", "ボク"], kunyomi: ["め", "ま-"], examples: ["目 (め) eye", "目的 (もくてき) purpose"] },
    { kanji: "耳", level: "小1", meanings: ["ear"], onyomi: ["ジ"], kunyomi: ["みみ"], examples: ["耳 (みみ) ear", "耳鼻科 (じびか) ENT clinic"] },
    { kanji: "手", level: "小1", meanings: ["hand"], onyomi: ["シュ"], kunyomi: ["て", "た-"], examples: ["手 (て) hand", "上手 (じょうず) skillful"] },
    { kanji: "足", level: "小1", meanings: ["foot", "leg", "enough"], onyomi: ["ソク"], kunyomi: ["あし", "た-りる"], examples: ["足 (あし) foot/leg", "足りる (たりる) to be enough"] },
    { kanji: "力", level: "小1", meanings: ["power", "strength"], onyomi: ["リョク", "リキ"], kunyomi: ["ちから"], examples: ["力 (ちから) strength", "電力 (でんりょく) electric power"] },
    { kanji: "女", level: "小1", meanings: ["woman", "female"], onyomi: ["ジョ", "ニョ"], kunyomi: ["おんな", "め-"], examples: ["女 (おんな) woman", "女性 (じょせい) female"] },
    { kanji: "男", level: "小1", meanings: ["man", "male"], onyomi: ["ダン", "ナン"], kunyomi: ["おとこ"], examples: ["男 (おとこ) man", "男性 (だんせい) male"] },
    { kanji: "子", level: "小1", meanings: ["child"], onyomi: ["シ", "ス"], kunyomi: ["こ", "ね"], examples: ["子供 (こども) child", "子 (こ) child"] },
    { kanji: "大", level: "小1", meanings: ["big", "large"], onyomi: ["ダイ", "タイ"], kunyomi: ["おお-きい", "おお-"], examples: ["大きい (おおきい) big", "大学 (だいがく) university"] },
    { kanji: "小", level: "小1", meanings: ["small", "little"], onyomi: ["ショウ"], kunyomi: ["ちい-さい", "こ-", "お-"], examples: ["小さい (ちいさい) small", "小学校 (しょうがっこう) elementary school"] },
    { kanji: "中", level: "小1", meanings: ["middle", "inside"], onyomi: ["チュウ"], kunyomi: ["なか"], examples: ["中 (なか) inside", "中学校 (ちゅうがっこう) middle school"] },
    { kanji: "上", level: "小1", meanings: ["up", "above"], onyomi: ["ジョウ", "ショウ"], kunyomi: ["うえ", "あ-げる", "のぼ-る"], examples: ["上 (うえ) above", "上手 (じょうず) skillful"] },
    { kanji: "下", level: "小1", meanings: ["down", "below"], onyomi: ["カ", "ゲ"], kunyomi: ["した", "さ-げる", "くだ-る"], examples: ["下 (した) below", "地下 (ちか) underground"] },
    { kanji: "左", level: "小1", meanings: ["left"], onyomi: ["サ"], kunyomi: ["ひだり"], examples: ["左 (ひだり) left", "左右 (さゆう) left and right"] },
    { kanji: "右", level: "小1", meanings: ["right"], onyomi: ["ウ", "ユウ"], kunyomi: ["みぎ"], examples: ["右 (みぎ) right", "右折 (うせつ) right turn"] },
    { kanji: "前", level: "小1", meanings: ["front", "before"], onyomi: ["ゼン"], kunyomi: ["まえ"], examples: ["前 (まえ) front/before", "名前 (なまえ) name"] },
    { kanji: "後", level: "小1", meanings: ["behind", "after"], onyomi: ["ゴ", "コウ"], kunyomi: ["うし-ろ", "あと"], examples: ["後 (あと) after", "午後 (ごご) afternoon"] },
    { kanji: "本", level: "小1", meanings: ["book", "origin"], onyomi: ["ホン"], kunyomi: ["もと"], examples: ["本 (ほん) book", "日本 (にほん) Japan"] },
    { kanji: "文", level: "小1", meanings: ["sentence", "writing"], onyomi: ["ブン", "モン"], kunyomi: ["ふみ"], examples: ["文 (ぶん) sentence", "文化 (ぶんか) culture"] },
    { kanji: "字", level: "小1", meanings: ["character", "letter"], onyomi: ["ジ"], kunyomi: ["あざ"], examples: ["漢字 (かんじ) kanji", "字 (じ) character"] },
    { kanji: "学", level: "小1", meanings: ["study", "learning"], onyomi: ["ガク"], kunyomi: ["まな-ぶ"], examples: ["学校 (がっこう) school", "学生 (がくせい) student"] },
    { kanji: "校", level: "小1", meanings: ["school"], onyomi: ["コウ"], kunyomi: [], examples: ["学校 (がっこう) school", "高校 (こうこう) high school"] },
    { kanji: "先", level: "小1", meanings: ["previous", "ahead", "tip"], onyomi: ["セン"], kunyomi: ["さき"], examples: ["先生 (せんせい) teacher", "先 (さき) ahead"] },
    { kanji: "生", level: "小1", meanings: ["life", "birth"], onyomi: ["セイ", "ショウ"], kunyomi: ["い-きる", "う-まれる", "なま"], examples: ["先生 (せんせい) teacher", "学生 (がくせい) student"] },
    { kanji: "気", level: "小1", meanings: ["spirit", "feeling", "atmosphere"], onyomi: ["キ", "ケ"], kunyomi: [], examples: ["天気 (てんき) weather", "気分 (きぶん) feeling"] },
    { kanji: "天", level: "小1", meanings: ["sky", "heaven"], onyomi: ["テン"], kunyomi: ["あめ", "あま-"], examples: ["天気 (てんき) weather", "天国 (てんごく) heaven"] },
    { kanji: "白", level: "小1", meanings: ["white"], onyomi: ["ハク", "ビャク"], kunyomi: ["しろ", "しろ-い"], examples: ["白い (しろい) white", "白黒 (しろくろ) black and white"] },
    { kanji: "赤", level: "小1", meanings: ["red"], onyomi: ["セキ", "シャク"], kunyomi: ["あか", "あか-い"], examples: ["赤い (あかい) red", "赤ちゃん (あかちゃん) baby"] },
    { kanji: "青", level: "小1", meanings: ["blue", "green"], onyomi: ["セイ", "ショウ"], kunyomi: ["あお", "あお-い"], examples: ["青い (あおい) blue", "青春 (せいしゅん) youth"] },
    { kanji: "花", level: "小1", meanings: ["flower"], onyomi: ["カ"], kunyomi: ["はな"], examples: ["花 (はな) flower", "花見 (はなみ) cherry blossom viewing"] },
    { kanji: "雨", level: "小1", meanings: ["rain"], onyomi: ["ウ"], kunyomi: ["あめ", "あま-"], examples: ["雨 (あめ) rain", "雨天 (うてん) rainy weather"] },
    { kanji: "空", level: "小1", meanings: ["sky", "empty"], onyomi: ["クウ"], kunyomi: ["そら", "から", "す-く"], examples: ["空 (そら) sky", "空港 (くうこう) airport"] },
    { kanji: "森", level: "小1", meanings: ["forest"], onyomi: ["シン"], kunyomi: ["もり"], examples: ["森 (もり) forest", "森林 (しんりん) forest/woods"] },
    { kanji: "林", level: "小1", meanings: ["forest", "grove"], onyomi: ["リン"], kunyomi: ["はやし"], examples: ["林 (はやし) grove", "林業 (りんぎょう) forestry"] },
    { kanji: "石", level: "小1", meanings: ["stone", "rock"], onyomi: ["セキ", "シャク", "コク"], kunyomi: ["いし"], examples: ["石 (いし) stone", "石油 (せきゆ) petroleum"] },
    { kanji: "竹", level: "小1", meanings: ["bamboo"], onyomi: ["チク"], kunyomi: ["たけ"], examples: ["竹 (たけ) bamboo", "竹林 (ちくりん) bamboo grove"] },
    { kanji: "犬", level: "小1", meanings: ["dog"], onyomi: ["ケン"], kunyomi: ["いぬ"], examples: ["犬 (いぬ) dog", "愛犬 (あいけん) pet dog"] },
    { kanji: "虫", level: "小1", meanings: ["insect", "bug"], onyomi: ["チュウ"], kunyomi: ["むし"], examples: ["虫 (むし) insect", "昆虫 (こんちゅう) insect"] },
    { kanji: "貝", level: "小1", meanings: ["shell", "shellfish"], onyomi: ["バイ"], kunyomi: ["かい"], examples: ["貝 (かい) shell", "貝殻 (かいがら) seashell"] },
    { kanji: "王", level: "小1", meanings: ["king", "ruler"], onyomi: ["オウ"], kunyomi: [], examples: ["王 (おう) king", "国王 (こくおう) king/monarch"] },
    { kanji: "玉", level: "小1", meanings: ["ball", "jewel"], onyomi: ["ギョク"], kunyomi: ["たま"], examples: ["玉 (たま) ball/jewel", "目玉 (めだま) eyeball"] },
    { kanji: "正", level: "小1", meanings: ["correct", "proper"], onyomi: ["セイ", "ショウ"], kunyomi: ["ただ-しい", "まさ"], examples: ["正しい (ただしい) correct", "正月 (しょうがつ) New Year"] },
    { kanji: "音", level: "小1", meanings: ["sound", "noise"], onyomi: ["オン", "イン"], kunyomi: ["おと", "ね"], examples: ["音楽 (おんがく) music", "音 (おと) sound"] },
    { kanji: "見", level: "小1", meanings: ["see", "look", "watch"], onyomi: ["ケン"], kunyomi: ["み-る", "み-せる", "み-える"], examples: ["見る (みる) to see", "見せる (みせる) to show"] },
    { kanji: "立", level: "小1", meanings: ["stand"], onyomi: ["リツ", "リュウ"], kunyomi: ["た-つ", "た-てる"], examples: ["立つ (たつ) to stand", "立場 (たちば) standpoint"] },
    { kanji: "入", level: "小1", meanings: ["enter", "put in"], onyomi: ["ニュウ"], kunyomi: ["い-る", "い-れる", "はい-る"], examples: ["入る (はいる) to enter", "入口 (いりぐち) entrance"] },
    { kanji: "出", level: "小1", meanings: ["exit", "come out"], onyomi: ["シュツ", "スイ"], kunyomi: ["で-る", "だ-す"], examples: ["出る (でる) to exit", "出口 (でぐち) exit"] },
    { kanji: "休", level: "小1", meanings: ["rest", "holiday"], onyomi: ["キュウ"], kunyomi: ["やす-む", "やす-み"], examples: ["休む (やすむ) to rest", "休日 (きゅうじつ) holiday"] },
    { kanji: "村", level: "小1", meanings: ["village"], onyomi: ["ソン"], kunyomi: ["むら"], examples: ["村 (むら) village", "農村 (のうそん) farming village"] },
    { kanji: "町", level: "小1", meanings: ["town", "city block"], onyomi: ["チョウ"], kunyomi: ["まち"], examples: ["町 (まち) town", "下町 (したまち) old town district"] },
    { kanji: "外", level: "小1", meanings: ["outside", "foreign"], onyomi: ["ガイ", "ゲ"], kunyomi: ["そと", "ほか"], examples: ["外 (そと) outside", "外国 (がいこく) foreign country"] },
    { kanji: "名", level: "小1", meanings: ["name", "famous"], onyomi: ["メイ", "ミョウ"], kunyomi: ["な"], examples: ["名前 (なまえ) name", "名刺 (めいし) business card"] },

    // ── 小2 (Grade 2 — 160 kanji) ───────────────────────────────
    { kanji: "万", level: "小2", meanings: ["ten thousand"], onyomi: ["マン", "バン"], kunyomi: [], examples: ["一万 (いちまん) 10,000", "万能 (ばんのう) all-purpose"] },
    { kanji: "元", level: "小2", meanings: ["origin", "former", "healthy"], onyomi: ["ゲン", "ガン"], kunyomi: ["もと"], examples: ["元気 (げんき) healthy/lively", "元 (もと) origin/former"] },
    { kanji: "父", level: "小2", meanings: ["father"], onyomi: ["フ"], kunyomi: ["ちち"], examples: ["父 (ちち) father", "お父さん (おとうさん) father (polite)"] },
    { kanji: "母", level: "小2", meanings: ["mother"], onyomi: ["ボ"], kunyomi: ["はは"], examples: ["母 (はは) mother", "お母さん (おかあさん) mother (polite)"] },
    { kanji: "兄", level: "小2", meanings: ["older brother"], onyomi: ["ケイ", "キョウ"], kunyomi: ["あに"], examples: ["兄 (あに) older brother", "兄弟 (きょうだい) siblings"] },
    { kanji: "姉", level: "小2", meanings: ["older sister"], onyomi: ["シ"], kunyomi: ["あね"], examples: ["姉 (あね) older sister", "お姉さん (おねえさん) older sister (polite)"] },
    { kanji: "弟", level: "小2", meanings: ["younger brother"], onyomi: ["テイ", "ダイ", "デ"], kunyomi: ["おとうと"], examples: ["弟 (おとうと) younger brother", "兄弟 (きょうだい) siblings"] },
    { kanji: "妹", level: "小2", meanings: ["younger sister"], onyomi: ["マイ"], kunyomi: ["いもうと"], examples: ["妹 (いもうと) younger sister", "姉妹 (しまい) sisters"] },
    { kanji: "友", level: "小2", meanings: ["friend"], onyomi: ["ユウ"], kunyomi: ["とも"], examples: ["友達 (ともだち) friend", "友人 (ゆうじん) friend"] },
    { kanji: "体", level: "小2", meanings: ["body"], onyomi: ["タイ", "テイ"], kunyomi: ["からだ"], examples: ["体 (からだ) body", "体育 (たいいく) physical education"] },
    { kanji: "顔", level: "小2", meanings: ["face"], onyomi: ["ガン"], kunyomi: ["かお"], examples: ["顔 (かお) face", "笑顔 (えがお) smiling face"] },
    { kanji: "頭", level: "小2", meanings: ["head"], onyomi: ["トウ", "ズ", "ト"], kunyomi: ["あたま", "かしら"], examples: ["頭 (あたま) head", "頭痛 (ずつう) headache"] },
    { kanji: "首", level: "小2", meanings: ["neck", "head"], onyomi: ["シュ"], kunyomi: ["くび"], examples: ["首 (くび) neck", "首相 (しゅしょう) prime minister"] },
    { kanji: "心", level: "小2", meanings: ["heart", "mind"], onyomi: ["シン"], kunyomi: ["こころ"], examples: ["心 (こころ) heart/mind", "心配 (しんぱい) worry"] },
    { kanji: "毛", level: "小2", meanings: ["hair", "fur"], onyomi: ["モウ"], kunyomi: ["け"], examples: ["毛 (け) hair/fur", "毛布 (もうふ) blanket"] },
    { kanji: "歩", level: "小2", meanings: ["walk", "step"], onyomi: ["ホ", "ブ"], kunyomi: ["ある-く", "あゆ-む"], examples: ["歩く (あるく) to walk", "散歩 (さんぽ) walk/stroll"] },
    { kanji: "走", level: "小2", meanings: ["run"], onyomi: ["ソウ"], kunyomi: ["はし-る"], examples: ["走る (はしる) to run", "競走 (きょうそう) race"] },
    { kanji: "食", level: "小2", meanings: ["eat", "food"], onyomi: ["ショク", "ジキ"], kunyomi: ["た-べる", "く-う"], examples: ["食べる (たべる) to eat", "食事 (しょくじ) meal"] },
    { kanji: "飲", level: "小2", meanings: ["drink"], onyomi: ["イン"], kunyomi: ["の-む"], examples: ["飲む (のむ) to drink", "飲み物 (のみもの) beverage"] },
    { kanji: "読", level: "小2", meanings: ["read"], onyomi: ["ドク", "トク"], kunyomi: ["よ-む"], examples: ["読む (よむ) to read", "読書 (どくしょ) reading"] },
    { kanji: "書", level: "小2", meanings: ["write"], onyomi: ["ショ"], kunyomi: ["か-く"], examples: ["書く (かく) to write", "書類 (しょるい) documents"] },
    { kanji: "聞", level: "小2", meanings: ["hear", "listen", "ask"], onyomi: ["ブン", "モン"], kunyomi: ["き-く", "き-こえる"], examples: ["聞く (きく) to hear", "新聞 (しんぶん) newspaper"] },
    { kanji: "話", level: "小2", meanings: ["talk", "story"], onyomi: ["ワ"], kunyomi: ["はな-す", "はなし"], examples: ["話す (はなす) to talk", "電話 (でんわ) telephone"] },
    { kanji: "言", level: "小2", meanings: ["say", "word"], onyomi: ["ゲン", "ゴン"], kunyomi: ["い-う", "こと"], examples: ["言う (いう) to say", "言葉 (ことば) word/language"] },
    { kanji: "売", level: "小2", meanings: ["sell"], onyomi: ["バイ"], kunyomi: ["う-る", "う-れる"], examples: ["売る (うる) to sell", "販売 (はんばい) sales"] },
    { kanji: "買", level: "小2", meanings: ["buy"], onyomi: ["バイ"], kunyomi: ["か-う"], examples: ["買う (かう) to buy", "買い物 (かいもの) shopping"] },
    { kanji: "来", level: "小2", meanings: ["come"], onyomi: ["ライ"], kunyomi: ["く-る", "き-", "こ-"], examples: ["来る (くる) to come", "来年 (らいねん) next year"] },
    { kanji: "行", level: "小2", meanings: ["go", "conduct"], onyomi: ["コウ", "ギョウ", "アン"], kunyomi: ["い-く", "おこな-う"], examples: ["行く (いく) to go", "旅行 (りょこう) travel"] },
    { kanji: "帰", level: "小2", meanings: ["return", "go back"], onyomi: ["キ"], kunyomi: ["かえ-る", "かえ-す"], examples: ["帰る (かえる) to return home", "帰国 (きこく) return to country"] },
    { kanji: "会", level: "小2", meanings: ["meet", "meeting", "association"], onyomi: ["カイ", "エ"], kunyomi: ["あ-う"], examples: ["会う (あう) to meet", "会社 (かいしゃ) company"] },
    { kanji: "回", level: "小2", meanings: ["turn", "time(s)"], onyomi: ["カイ", "エ"], kunyomi: ["まわ-る", "まわ-す"], examples: ["回る (まわる) to turn", "一回 (いっかい) once"] },
    { kanji: "思", level: "小2", meanings: ["think", "feel"], onyomi: ["シ"], kunyomi: ["おも-う"], examples: ["思う (おもう) to think/feel", "思い出 (おもいで) memory"] },
    { kanji: "知", level: "小2", meanings: ["know"], onyomi: ["チ"], kunyomi: ["し-る"], examples: ["知る (しる) to know", "知識 (ちしき) knowledge"] },
    { kanji: "作", level: "小2", meanings: ["make", "create"], onyomi: ["サク", "サ"], kunyomi: ["つく-る"], examples: ["作る (つくる) to make", "作品 (さくひん) work/piece"] },
    { kanji: "使", level: "小2", meanings: ["use", "employ"], onyomi: ["シ"], kunyomi: ["つか-う"], examples: ["使う (つかう) to use", "大使 (たいし) ambassador"] },
    { kanji: "切", level: "小2", meanings: ["cut", "important"], onyomi: ["セツ", "サイ"], kunyomi: ["き-る", "き-れる"], examples: ["切る (きる) to cut", "大切 (たいせつ) important"] },
    { kanji: "国", level: "小2", meanings: ["country", "nation"], onyomi: ["コク"], kunyomi: ["くに"], examples: ["国 (くに) country", "外国 (がいこく) foreign country"] },
    { kanji: "語", level: "小2", meanings: ["language", "word"], onyomi: ["ゴ"], kunyomi: ["かた-る"], examples: ["日本語 (にほんご) Japanese", "英語 (えいご) English"] },
    { kanji: "東", level: "小2", meanings: ["east"], onyomi: ["トウ"], kunyomi: ["ひがし"], examples: ["東 (ひがし) east", "東京 (とうきょう) Tokyo"] },
    { kanji: "西", level: "小2", meanings: ["west"], onyomi: ["セイ", "サイ"], kunyomi: ["にし"], examples: ["西 (にし) west", "西洋 (せいよう) the West"] },
    { kanji: "南", level: "小2", meanings: ["south"], onyomi: ["ナン", "ナ"], kunyomi: ["みなみ"], examples: ["南 (みなみ) south", "南米 (なんべい) South America"] },
    { kanji: "北", level: "小2", meanings: ["north"], onyomi: ["ホク"], kunyomi: ["きた"], examples: ["北 (きた) north", "北海道 (ほっかいどう) Hokkaido"] },
    { kanji: "春", level: "小2", meanings: ["spring"], onyomi: ["シュン"], kunyomi: ["はる"], examples: ["春 (はる) spring", "青春 (せいしゅん) youth"] },
    { kanji: "夏", level: "小2", meanings: ["summer"], onyomi: ["カ", "ゲ"], kunyomi: ["なつ"], examples: ["夏 (なつ) summer", "夏休み (なつやすみ) summer vacation"] },
    { kanji: "秋", level: "小2", meanings: ["autumn", "fall"], onyomi: ["シュウ"], kunyomi: ["あき"], examples: ["秋 (あき) autumn", "秋分 (しゅうぶん) autumnal equinox"] },
    { kanji: "冬", level: "小2", meanings: ["winter"], onyomi: ["トウ"], kunyomi: ["ふゆ"], examples: ["冬 (ふゆ) winter", "冬休み (ふゆやすみ) winter vacation"] },
    { kanji: "朝", level: "小2", meanings: ["morning"], onyomi: ["チョウ"], kunyomi: ["あさ"], examples: ["今朝 (けさ) this morning", "朝食 (ちょうしょく) breakfast"] },
    { kanji: "昼", level: "小2", meanings: ["noon", "daytime"], onyomi: ["チュウ"], kunyomi: ["ひる"], examples: ["昼 (ひる) noon", "昼食 (ちゅうしょく) lunch"] },
    { kanji: "夜", level: "小2", meanings: ["night", "evening"], onyomi: ["ヤ"], kunyomi: ["よ", "よる"], examples: ["今夜 (こんや) tonight", "夜 (よる) night"] },
    { kanji: "週", level: "小2", meanings: ["week"], onyomi: ["シュウ"], kunyomi: [], examples: ["今週 (こんしゅう) this week", "来週 (らいしゅう) next week"] },
    { kanji: "曜", level: "小2", meanings: ["day of week"], onyomi: ["ヨウ"], kunyomi: [], examples: ["月曜日 (げつようび) Monday", "何曜日 (なんようび) what day"] },
    { kanji: "今", level: "小2", meanings: ["now", "present"], onyomi: ["コン", "キン"], kunyomi: ["いま"], examples: ["今 (いま) now", "今日 (きょう) today"] },
    { kanji: "毎", level: "小2", meanings: ["every", "each"], onyomi: ["マイ"], kunyomi: [], examples: ["毎日 (まいにち) every day", "毎年 (まいとし) every year"] },
    { kanji: "明", level: "小2", meanings: ["bright", "clear", "next"], onyomi: ["メイ", "ミョウ"], kunyomi: ["あか-るい", "あ-ける", "あき-らか"], examples: ["明るい (あかるい) bright", "明日 (あした) tomorrow"] },
    { kanji: "古", level: "小2", meanings: ["old (things)"], onyomi: ["コ"], kunyomi: ["ふる-い", "ふる-す"], examples: ["古い (ふるい) old", "中古 (ちゅうこ) used/secondhand"] },
    { kanji: "新", level: "小2", meanings: ["new"], onyomi: ["シン"], kunyomi: ["あたら-しい", "あら-", "にい-"], examples: ["新しい (あたらしい) new", "新聞 (しんぶん) newspaper"] },
    { kanji: "高", level: "小2", meanings: ["tall", "expensive", "high"], onyomi: ["コウ"], kunyomi: ["たか-い", "たか-まる"], examples: ["高い (たかい) tall/expensive", "高校 (こうこう) high school"] },
    { kanji: "長", level: "小2", meanings: ["long", "leader"], onyomi: ["チョウ"], kunyomi: ["なが-い", "おさ"], examples: ["長い (ながい) long", "社長 (しゃちょう) company president"] },
    { kanji: "強", level: "小2", meanings: ["strong"], onyomi: ["キョウ", "ゴウ"], kunyomi: ["つよ-い", "つよ-まる"], examples: ["強い (つよい) strong", "勉強 (べんきょう) study"] },
    { kanji: "弱", level: "小2", meanings: ["weak"], onyomi: ["ジャク"], kunyomi: ["よわ-い", "よわ-まる"], examples: ["弱い (よわい) weak", "弱点 (じゃくてん) weak point"] },
    { kanji: "太", level: "小2", meanings: ["fat", "thick"], onyomi: ["タイ", "タ"], kunyomi: ["ふと-い", "ふと-る"], examples: ["太い (ふとい) thick/fat", "太る (ふとる) to gain weight"] },
    { kanji: "細", level: "小2", meanings: ["thin", "fine", "detail"], onyomi: ["サイ"], kunyomi: ["ほそ-い", "こま-かい"], examples: ["細い (ほそい) thin", "細かい (こまかい) fine/detailed"] },
    { kanji: "広", level: "小2", meanings: ["wide", "broad"], onyomi: ["コウ"], kunyomi: ["ひろ-い", "ひろ-げる"], examples: ["広い (ひろい) wide/spacious", "広告 (こうこく) advertisement"] },
    { kanji: "色", level: "小2", meanings: ["color"], onyomi: ["ショク", "シキ"], kunyomi: ["いろ"], examples: ["色 (いろ) color", "茶色 (ちゃいろ) brown"] },
    { kanji: "黄", level: "小2", meanings: ["yellow"], onyomi: ["コウ", "オウ"], kunyomi: ["き", "こ-"], examples: ["黄色 (きいろ) yellow", "黄金 (おうごん) gold"] },
    { kanji: "黒", level: "小2", meanings: ["black"], onyomi: ["コク"], kunyomi: ["くろ", "くろ-い"], examples: ["黒い (くろい) black", "黒板 (こくばん) blackboard"] },
    { kanji: "茶", level: "小2", meanings: ["tea", "brown"], onyomi: ["チャ", "サ"], kunyomi: [], examples: ["お茶 (おちゃ) tea", "茶色 (ちゃいろ) brown"] },
    { kanji: "紙", level: "小2", meanings: ["paper"], onyomi: ["シ"], kunyomi: ["かみ"], examples: ["紙 (かみ) paper", "手紙 (てがみ) letter"] },
    { kanji: "家", level: "小2", meanings: ["house", "home", "family"], onyomi: ["カ", "ケ"], kunyomi: ["いえ", "や"], examples: ["家 (いえ) house", "家族 (かぞく) family"] },
    { kanji: "室", level: "小2", meanings: ["room"], onyomi: ["シツ"], kunyomi: ["むろ"], examples: ["教室 (きょうしつ) classroom", "洋室 (ようしつ) Western-style room"] },
    { kanji: "店", level: "小2", meanings: ["shop", "store"], onyomi: ["テン"], kunyomi: ["みせ"], examples: ["お店 (おみせ) shop", "書店 (しょてん) bookstore"] },
    { kanji: "道", level: "小2", meanings: ["road", "way"], onyomi: ["ドウ", "トウ"], kunyomi: ["みち"], examples: ["道 (みち) road", "北海道 (ほっかいどう) Hokkaido"] },
    { kanji: "市", level: "小2", meanings: ["city", "market"], onyomi: ["シ"], kunyomi: ["いち"], examples: ["市 (し) city", "市場 (いちば) market"] },
    { kanji: "海", level: "小2", meanings: ["sea", "ocean"], onyomi: ["カイ"], kunyomi: ["うみ"], examples: ["海 (うみ) sea", "海外 (かいがい) overseas"] },
    { kanji: "池", level: "小2", meanings: ["pond"], onyomi: ["チ"], kunyomi: ["いけ"], examples: ["池 (いけ) pond", "電池 (でんち) battery"] },
    { kanji: "岩", level: "小2", meanings: ["rock", "boulder"], onyomi: ["ガン"], kunyomi: ["いわ"], examples: ["岩 (いわ) rock", "岩石 (がんせき) rock/stone"] },
    { kanji: "地", level: "小2", meanings: ["ground", "earth"], onyomi: ["チ", "ジ"], kunyomi: [], examples: ["地図 (ちず) map", "地下鉄 (ちかてつ) subway"] },
    { kanji: "野", level: "小2", meanings: ["field", "plains"], onyomi: ["ヤ"], kunyomi: ["の"], examples: ["野原 (のはら) field", "野菜 (やさい) vegetables"] },
    { kanji: "光", level: "小2", meanings: ["light"], onyomi: ["コウ"], kunyomi: ["ひかり", "ひか-る"], examples: ["光 (ひかり) light", "観光 (かんこう) sightseeing"] },
    { kanji: "星", level: "小2", meanings: ["star"], onyomi: ["セイ", "ショウ"], kunyomi: ["ほし"], examples: ["星 (ほし) star", "流れ星 (ながれぼし) shooting star"] },
    { kanji: "晴", level: "小2", meanings: ["clear up", "sunny"], onyomi: ["セイ"], kunyomi: ["は-れる", "は-らす"], examples: ["晴れる (はれる) to clear up", "晴天 (せいてん) clear weather"] },
    { kanji: "雪", level: "小2", meanings: ["snow"], onyomi: ["セツ"], kunyomi: ["ゆき"], examples: ["雪 (ゆき) snow", "雪国 (ゆきぐに) snowy country"] },
    { kanji: "風", level: "小2", meanings: ["wind", "style"], onyomi: ["フウ", "フ"], kunyomi: ["かぜ", "かざ-"], examples: ["風 (かぜ) wind", "台風 (たいふう) typhoon"] },
    { kanji: "電", level: "小2", meanings: ["electricity"], onyomi: ["デン"], kunyomi: [], examples: ["電話 (でんわ) telephone", "電車 (でんしゃ) train"] },
    { kanji: "車", level: "小2", meanings: ["car", "vehicle"], onyomi: ["シャ"], kunyomi: ["くるま"], examples: ["車 (くるま) car", "電車 (でんしゃ) train"] },
    { kanji: "馬", level: "小2", meanings: ["horse"], onyomi: ["バ", "マ"], kunyomi: ["うま", "ま-"], examples: ["馬 (うま) horse", "乗馬 (じょうば) horse riding"] },
    { kanji: "牛", level: "小2", meanings: ["cow", "beef"], onyomi: ["ギュウ"], kunyomi: ["うし"], examples: ["牛 (うし) cow", "牛乳 (ぎゅうにゅう) milk"] },
    { kanji: "魚", level: "小2", meanings: ["fish"], onyomi: ["ギョ"], kunyomi: ["さかな", "うお"], examples: ["魚 (さかな) fish", "金魚 (きんぎょ) goldfish"] },
    { kanji: "鳥", level: "小2", meanings: ["bird"], onyomi: ["チョウ"], kunyomi: ["とり"], examples: ["鳥 (とり) bird", "野鳥 (やちょう) wild bird"] },
    { kanji: "肉", level: "小2", meanings: ["meat", "flesh"], onyomi: ["ニク"], kunyomi: [], examples: ["肉 (にく) meat", "牛肉 (ぎゅうにく) beef"] },
    { kanji: "米", level: "小2", meanings: ["rice", "America"], onyomi: ["ベイ", "マイ"], kunyomi: ["こめ"], examples: ["米 (こめ) rice (uncooked)", "米国 (べいこく) USA"] },
    { kanji: "麦", level: "小2", meanings: ["wheat", "barley"], onyomi: ["バク"], kunyomi: ["むぎ"], examples: ["麦 (むぎ) wheat/barley", "小麦 (こむぎ) wheat"] },
    { kanji: "刀", level: "小2", meanings: ["sword", "knife"], onyomi: ["トウ"], kunyomi: ["かたな"], examples: ["刀 (かたな) sword", "日本刀 (にほんとう) Japanese sword"] },
    { kanji: "工", level: "小2", meanings: ["construction", "craft"], onyomi: ["コウ", "ク"], kunyomi: [], examples: ["工場 (こうじょう) factory", "工事 (こうじ) construction"] },
    { kanji: "計", level: "小2", meanings: ["measure", "plan", "total"], onyomi: ["ケイ"], kunyomi: ["はか-る"], examples: ["時計 (とけい) clock/watch", "計画 (けいかく) plan"] },
    { kanji: "算", level: "小2", meanings: ["calculate", "count"], onyomi: ["サン"], kunyomi: [], examples: ["計算 (けいさん) calculation", "算数 (さんすう) arithmetic"] },
    { kanji: "数", level: "小2", meanings: ["number", "count"], onyomi: ["スウ", "ス"], kunyomi: ["かず", "かぞ-える"], examples: ["数 (かず) number", "数学 (すうがく) mathematics"] },
    { kanji: "半", level: "小2", meanings: ["half"], onyomi: ["ハン"], kunyomi: ["なか-ば"], examples: ["半分 (はんぶん) half", "一時半 (いちじはん) 1:30"] },
    { kanji: "分", level: "小2", meanings: ["minute", "part", "understand"], onyomi: ["ブン", "フン", "ブ"], kunyomi: ["わ-かる", "わ-ける"], examples: ["三十分 (さんじゅっぷん) 30 minutes", "分かる (わかる) to understand"] },
    { kanji: "時", level: "小2", meanings: ["time", "hour"], onyomi: ["ジ"], kunyomi: ["とき"], examples: ["三時 (さんじ) 3 o'clock", "時間 (じかん) time"] },
    { kanji: "間", level: "小2", meanings: ["interval", "between"], onyomi: ["カン", "ケン"], kunyomi: ["あいだ", "ま"], examples: ["時間 (じかん) time", "人間 (にんげん) human being"] },
    { kanji: "門", level: "小2", meanings: ["gate"], onyomi: ["モン"], kunyomi: ["かど"], examples: ["門 (もん) gate", "専門 (せんもん) specialty"] },
    { kanji: "近", level: "小2", meanings: ["near", "close"], onyomi: ["キン"], kunyomi: ["ちか-い", "ちか-づく"], examples: ["近い (ちかい) near", "近所 (きんじょ) neighborhood"] },
    { kanji: "遠", level: "小2", meanings: ["far", "distant"], onyomi: ["エン", "オン"], kunyomi: ["とお-い"], examples: ["遠い (とおい) far", "遠足 (えんそく) excursion"] },
    { kanji: "通", level: "小2", meanings: ["pass through", "commute"], onyomi: ["ツウ", "ツ"], kunyomi: ["とお-る", "かよ-う"], examples: ["通る (とおる) to pass", "交通 (こうつう) traffic"] },
    { kanji: "歌", level: "小2", meanings: ["song", "sing"], onyomi: ["カ"], kunyomi: ["うた", "うた-う"], examples: ["歌 (うた) song", "歌手 (かしゅ) singer"] },
    { kanji: "絵", level: "小2", meanings: ["picture", "painting"], onyomi: ["カイ", "エ"], kunyomi: [], examples: ["絵 (え) picture/painting", "絵本 (えほん) picture book"] },
    { kanji: "園", level: "小2", meanings: ["garden", "park"], onyomi: ["エン"], kunyomi: ["その"], examples: ["公園 (こうえん) park", "動物園 (どうぶつえん) zoo"] },
    { kanji: "科", level: "小2", meanings: ["department", "subject"], onyomi: ["カ"], kunyomi: [], examples: ["科学 (かがく) science", "科目 (かもく) subject"] },
    { kanji: "図", level: "小2", meanings: ["drawing", "map", "plan"], onyomi: ["ズ", "ト"], kunyomi: ["はか-る"], examples: ["地図 (ちず) map", "図書館 (としょかん) library"] },
    { kanji: "台", level: "小2", meanings: ["rack", "stand", "counter"], onyomi: ["ダイ", "タイ"], kunyomi: [], examples: ["台所 (だいどころ) kitchen", "舞台 (ぶたい) stage"] },
    { kanji: "同", level: "小2", meanings: ["same", "agree"], onyomi: ["ドウ"], kunyomi: ["おな-じ"], examples: ["同じ (おなじ) same", "同意 (どうい) agreement"] },
    { kanji: "番", level: "小2", meanings: ["number", "turn", "watch"], onyomi: ["バン"], kunyomi: [], examples: ["番号 (ばんごう) number", "一番 (いちばん) number one/most"] },
    { kanji: "組", level: "小2", meanings: ["group", "class", "assemble"], onyomi: ["ソ"], kunyomi: ["く-む", "くみ"], examples: ["組 (くみ) group/class", "番組 (ばんぐみ) TV program"] },
    { kanji: "合", level: "小2", meanings: ["combine", "fit", "suit"], onyomi: ["ゴウ", "ガッ", "カッ"], kunyomi: ["あ-う", "あ-わせる"], examples: ["合う (あう) to fit/suit", "試合 (しあい) match/game"] },
    { kanji: "社", level: "小2", meanings: ["company", "shrine"], onyomi: ["シャ"], kunyomi: ["やしろ"], examples: ["会社 (かいしゃ) company", "社長 (しゃちょう) company president"] },
    { kanji: "交", level: "小2", meanings: ["mix", "mingle", "exchange"], onyomi: ["コウ"], kunyomi: ["ま-じる", "か-わす"], examples: ["交通 (こうつう) traffic", "交換 (こうかん) exchange"] },

    // ── 小3 (Grade 3 — 200 kanji) ───────────────────────────────
    { kanji: "悪", level: "小3", meanings: ["bad", "evil"], onyomi: ["アク", "オ"], kunyomi: ["わる-い"], examples: ["悪い (わるい) bad", "悪口 (わるくち) bad-mouthing"] },
    { kanji: "安", level: "小3", meanings: ["cheap", "relax", "safe"], onyomi: ["アン"], kunyomi: ["やす-い", "やす-らか"], examples: ["安い (やすい) cheap", "安全 (あんぜん) safe"] },
    { kanji: "暗", level: "小3", meanings: ["dark"], onyomi: ["アン"], kunyomi: ["くら-い"], examples: ["暗い (くらい) dark", "暗記 (あんき) memorization"] },
    { kanji: "医", level: "小3", meanings: ["medicine", "doctor"], onyomi: ["イ"], kunyomi: [], examples: ["医者 (いしゃ) doctor", "医学 (いがく) medicine"] },
    { kanji: "意", level: "小3", meanings: ["intention", "meaning"], onyomi: ["イ"], kunyomi: [], examples: ["意味 (いみ) meaning", "注意 (ちゅうい) attention/caution"] },
    { kanji: "育", level: "小3", meanings: ["raise", "grow up"], onyomi: ["イク"], kunyomi: ["そだ-てる", "そだ-つ"], examples: ["教育 (きょういく) education", "育てる (そだてる) to raise"] },
    { kanji: "員", level: "小3", meanings: ["member", "staff"], onyomi: ["イン"], kunyomi: [], examples: ["社員 (しゃいん) company employee", "店員 (てんいん) store clerk"] },
    { kanji: "院", level: "小3", meanings: ["institution", "temple"], onyomi: ["イン"], kunyomi: [], examples: ["病院 (びょういん) hospital", "大学院 (だいがくいん) graduate school"] },
    { kanji: "運", level: "小3", meanings: ["carry", "luck"], onyomi: ["ウン"], kunyomi: ["はこ-ぶ"], examples: ["運動 (うんどう) exercise", "運転 (うんてん) driving"] },
    { kanji: "映", level: "小3", meanings: ["reflect", "project"], onyomi: ["エイ"], kunyomi: ["うつ-る", "うつ-す", "は-える"], examples: ["映画 (えいが) movie", "映る (うつる) to be reflected"] },
    { kanji: "英", level: "小3", meanings: ["England", "hero"], onyomi: ["エイ"], kunyomi: [], examples: ["英語 (えいご) English", "英国 (えいこく) England"] },
    { kanji: "温", level: "小3", meanings: ["warm", "temperature"], onyomi: ["オン"], kunyomi: ["あたた-かい", "あたた-める"], examples: ["温かい (あたたかい) warm", "温度 (おんど) temperature"] },
    { kanji: "化", level: "小3", meanings: ["change", "transform"], onyomi: ["カ", "ケ"], kunyomi: ["ば-ける", "ば-かす"], examples: ["変化 (へんか) change", "文化 (ぶんか) culture"] },
    { kanji: "加", level: "小3", meanings: ["add", "increase", "join"], onyomi: ["カ"], kunyomi: ["くわ-える", "くわ-わる"], examples: ["加える (くわえる) to add", "参加 (さんか) participation"] },
    { kanji: "開", level: "小3", meanings: ["open"], onyomi: ["カイ"], kunyomi: ["あ-ける", "あ-く", "ひら-く"], examples: ["開ける (あける) to open", "開発 (かいはつ) development"] },
    { kanji: "感", level: "小3", meanings: ["feeling", "sense"], onyomi: ["カン"], kunyomi: [], examples: ["感じる (かんじる) to feel", "感謝 (かんしゃ) gratitude"] },
    { kanji: "館", level: "小3", meanings: ["building", "hall"], onyomi: ["カン"], kunyomi: ["やかた"], examples: ["図書館 (としょかん) library", "旅館 (りょかん) Japanese inn"] },
    { kanji: "漢", level: "小3", meanings: ["China", "Chinese character"], onyomi: ["カン"], kunyomi: [], examples: ["漢字 (かんじ) kanji", "漢方 (かんぽう) Chinese herbal medicine"] },
    { kanji: "起", level: "小3", meanings: ["wake up", "rise", "occur"], onyomi: ["キ"], kunyomi: ["お-きる", "お-こる", "お-こす"], examples: ["起きる (おきる) to wake up", "起こる (おこる) to occur"] },
    { kanji: "期", level: "小3", meanings: ["period", "time", "term"], onyomi: ["キ", "ゴ"], kunyomi: [], examples: ["期待 (きたい) expectation", "学期 (がっき) school term"] },
    { kanji: "急", level: "小3", meanings: ["hurry", "sudden"], onyomi: ["キュウ"], kunyomi: ["いそ-ぐ"], examples: ["急ぐ (いそぐ) to hurry", "急に (きゅうに) suddenly"] },
    { kanji: "球", level: "小3", meanings: ["ball", "sphere"], onyomi: ["キュウ"], kunyomi: ["たま"], examples: ["野球 (やきゅう) baseball", "地球 (ちきゅう) earth/globe"] },
    { kanji: "去", level: "小3", meanings: ["past", "leave"], onyomi: ["キョ", "コ"], kunyomi: ["さ-る"], examples: ["去年 (きょねん) last year", "過去 (かこ) the past"] },
    { kanji: "橋", level: "小3", meanings: ["bridge"], onyomi: ["キョウ"], kunyomi: ["はし"], examples: ["橋 (はし) bridge", "歩道橋 (ほどうきょう) pedestrian bridge"] },
    { kanji: "教", level: "小3", meanings: ["teach", "religion"], onyomi: ["キョウ"], kunyomi: ["おし-える", "おそ-わる"], examples: ["教える (おしえる) to teach", "教育 (きょういく) education"] },
    { kanji: "曲", level: "小3", meanings: ["musical piece", "bend"], onyomi: ["キョク"], kunyomi: ["ま-がる", "ま-げる"], examples: ["曲 (きょく) melody/piece", "曲がる (まがる) to bend/turn"] },
    { kanji: "局", level: "小3", meanings: ["bureau", "office", "situation"], onyomi: ["キョク"], kunyomi: [], examples: ["郵便局 (ゆうびんきょく) post office", "局 (きょく) bureau"] },
    { kanji: "区", level: "小3", meanings: ["district", "ward"], onyomi: ["ク"], kunyomi: [], examples: ["地区 (ちく) district", "区別 (くべつ) distinction"] },
    { kanji: "君", level: "小3", meanings: ["you (familiar)", "lord"], onyomi: ["クン"], kunyomi: ["きみ"], examples: ["君 (きみ) you (familiar)", "諸君 (しょくん) everyone"] },
    { kanji: "形", level: "小3", meanings: ["form", "shape"], onyomi: ["ケイ", "ギョウ"], kunyomi: ["かた", "かたち"], examples: ["形 (かたち) shape", "人形 (にんぎょう) doll"] },
    { kanji: "決", level: "小3", meanings: ["decide", "determine"], onyomi: ["ケツ"], kunyomi: ["き-める", "き-まる"], examples: ["決める (きめる) to decide", "決定 (けってい) decision"] },
    { kanji: "研", level: "小3", meanings: ["research", "polish"], onyomi: ["ケン"], kunyomi: ["と-ぐ"], examples: ["研究 (けんきゅう) research", "研究者 (けんきゅうしゃ) researcher"] },
    { kanji: "号", level: "小3", meanings: ["number", "name", "signal"], onyomi: ["ゴウ"], kunyomi: [], examples: ["番号 (ばんごう) number", "信号 (しんごう) traffic signal"] },
    { kanji: "港", level: "小3", meanings: ["harbor", "port"], onyomi: ["コウ"], kunyomi: ["みなと"], examples: ["港 (みなと) harbor", "空港 (くうこう) airport"] },
    { kanji: "考", level: "小3", meanings: ["think", "consider"], onyomi: ["コウ"], kunyomi: ["かんが-える"], examples: ["考える (かんがえる) to think", "考え (かんがえ) idea/thought"] },
    { kanji: "向", level: "小3", meanings: ["face", "direction", "toward"], onyomi: ["コウ"], kunyomi: ["む-く", "むこう"], examples: ["向く (むく) to face", "向こう (むこう) over there"] },
    { kanji: "根", level: "小3", meanings: ["root"], onyomi: ["コン"], kunyomi: ["ね"], examples: ["根 (ね) root", "根拠 (こんきょ) basis/grounds"] },
    { kanji: "祭", level: "小3", meanings: ["festival", "worship"], onyomi: ["サイ"], kunyomi: ["まつ-り", "まつ-る"], examples: ["祭り (まつり) festival", "祭日 (さいじつ) national holiday"] },
    { kanji: "仕", level: "小3", meanings: ["serve", "work"], onyomi: ["シ", "ジ"], kunyomi: [], examples: ["仕事 (しごと) work/job", "仕方 (しかた) way/method"] },
    { kanji: "始", level: "小3", meanings: ["begin", "start"], onyomi: ["シ"], kunyomi: ["はじ-める", "はじ-まる"], examples: ["始める (はじめる) to begin", "始まる (はじまる) to start"] },
    { kanji: "事", level: "小3", meanings: ["thing", "matter", "fact"], onyomi: ["ジ", "ズ"], kunyomi: ["こと"], examples: ["仕事 (しごと) work/job", "事故 (じこ) accident"] },
    { kanji: "自", level: "小3", meanings: ["self", "oneself"], onyomi: ["ジ", "シ"], kunyomi: ["みずか-ら"], examples: ["自分 (じぶん) oneself", "自動車 (じどうしゃ) automobile"] },
    { kanji: "式", level: "小3", meanings: ["ceremony", "formula", "style"], onyomi: ["シキ"], kunyomi: [], examples: ["式 (しき) ceremony/formula", "入学式 (にゅうがくしき) entrance ceremony"] },
    { kanji: "実", level: "小3", meanings: ["truth", "fruit", "real"], onyomi: ["ジツ", "シツ"], kunyomi: ["み", "みの-る"], examples: ["実は (じつは) actually", "実力 (じつりょく) true ability"] },
    { kanji: "写", level: "小3", meanings: ["copy", "photograph"], onyomi: ["シャ"], kunyomi: ["うつ-す", "うつ-る"], examples: ["写真 (しゃしん) photograph", "写す (うつす) to copy"] },
    { kanji: "指", level: "小3", meanings: ["finger", "point to"], onyomi: ["シ"], kunyomi: ["ゆび", "さ-す"], examples: ["指 (ゆび) finger", "指示 (しじ) instruction"] },
    { kanji: "持", level: "小3", meanings: ["hold", "carry", "have"], onyomi: ["ジ"], kunyomi: ["も-つ"], examples: ["持つ (もつ) to hold/have", "持ち物 (もちもの) belongings"] },
    { kanji: "死", level: "小3", meanings: ["die", "death"], onyomi: ["シ"], kunyomi: ["し-ぬ"], examples: ["死ぬ (しぬ) to die", "生死 (せいし) life and death"] },
    { kanji: "試", level: "小3", meanings: ["try", "test"], onyomi: ["シ"], kunyomi: ["こころ-みる", "ため-す"], examples: ["試験 (しけん) exam", "試合 (しあい) match/game"] },
    { kanji: "詩", level: "小3", meanings: ["poem", "poetry"], onyomi: ["シ"], kunyomi: [], examples: ["詩 (し) poem", "詩人 (しじん) poet"] },
    { kanji: "質", level: "小3", meanings: ["quality", "nature"], onyomi: ["シツ", "シチ", "チ"], kunyomi: ["たち"], examples: ["質問 (しつもん) question", "品質 (ひんしつ) quality"] },
    { kanji: "集", level: "小3", meanings: ["gather", "collect"], onyomi: ["シュウ"], kunyomi: ["あつ-まる", "あつ-める"], examples: ["集まる (あつまる) to gather", "集める (あつめる) to collect"] },
    { kanji: "習", level: "小3", meanings: ["learn", "practice"], onyomi: ["シュウ"], kunyomi: ["なら-う"], examples: ["習う (ならう) to learn", "練習 (れんしゅう) practice"] },
    { kanji: "終", level: "小3", meanings: ["end", "finish"], onyomi: ["シュウ"], kunyomi: ["お-わる", "お-える"], examples: ["終わる (おわる) to end", "終電 (しゅうでん) last train"] },
    { kanji: "受", level: "小3", meanings: ["receive", "accept"], onyomi: ["ジュ"], kunyomi: ["う-ける", "う-かる"], examples: ["受ける (うける) to receive", "受付 (うけつけ) reception"] },
    { kanji: "守", level: "小3", meanings: ["protect", "guard", "obey"], onyomi: ["シュ", "ス"], kunyomi: ["まも-る"], examples: ["守る (まもる) to protect", "守備 (しゅび) defense"] },
    { kanji: "宿", level: "小3", meanings: ["lodge", "inn", "homework"], onyomi: ["シュク"], kunyomi: ["やど", "やど-る"], examples: ["宿題 (しゅくだい) homework", "宿泊 (しゅくはく) overnight stay"] },
    { kanji: "所", level: "小3", meanings: ["place"], onyomi: ["ショ"], kunyomi: ["ところ"], examples: ["場所 (ばしょ) place", "台所 (だいどころ) kitchen"] },
    { kanji: "助", level: "小3", meanings: ["help", "assist"], onyomi: ["ジョ"], kunyomi: ["たす-ける", "たす-かる"], examples: ["助ける (たすける) to help", "助かる (たすかる) to be saved"] },
    { kanji: "乗", level: "小3", meanings: ["ride", "board"], onyomi: ["ジョウ"], kunyomi: ["の-る", "の-せる"], examples: ["乗る (のる) to ride", "乗り換え (のりかえ) transfer"] },
    { kanji: "植", level: "小3", meanings: ["plant", "grow"], onyomi: ["ショク"], kunyomi: ["う-える", "う-わる"], examples: ["植える (うえる) to plant", "植物 (しょくぶつ) plant"] },
    { kanji: "深", level: "小3", meanings: ["deep", "profound"], onyomi: ["シン"], kunyomi: ["ふか-い", "ふか-まる"], examples: ["深い (ふかい) deep", "深呼吸 (しんこきゅう) deep breath"] },
    { kanji: "申", level: "小3", meanings: ["say (humble)", "apply"], onyomi: ["シン"], kunyomi: ["もう-す"], examples: ["申す (もうす) to say (humble)", "申し込み (もうしこみ) application"] },
    { kanji: "身", level: "小3", meanings: ["body", "oneself"], onyomi: ["シン"], kunyomi: ["み"], examples: ["身体 (しんたい) body", "自身 (じしん) oneself"] },
    { kanji: "親", level: "小3", meanings: ["parent", "intimate"], onyomi: ["シン"], kunyomi: ["おや", "した-しい"], examples: ["親 (おや) parent", "親切 (しんせつ) kind"] },
    { kanji: "進", level: "小3", meanings: ["advance", "progress"], onyomi: ["シン"], kunyomi: ["すす-む", "すす-める"], examples: ["進む (すすむ) to advance", "進歩 (しんぽ) progress"] },
    { kanji: "消", level: "小3", meanings: ["erase", "extinguish"], onyomi: ["ショウ"], kunyomi: ["け-す", "き-える"], examples: ["消す (けす) to erase/turn off", "消える (きえる) to disappear"] },
    { kanji: "勝", level: "小3", meanings: ["win", "victory"], onyomi: ["ショウ"], kunyomi: ["か-つ", "かち"], examples: ["勝つ (かつ) to win", "勝利 (しょうり) victory"] },
    { kanji: "全", level: "小3", meanings: ["all", "whole"], onyomi: ["ゼン"], kunyomi: ["すべ-て", "まった-く"], examples: ["全部 (ぜんぶ) all", "全て (すべて) everything"] },
    { kanji: "想", level: "小3", meanings: ["idea", "think"], onyomi: ["ソウ", "ソ"], kunyomi: [], examples: ["想像 (そうぞう) imagination", "感想 (かんそう) impression"] },
    { kanji: "送", level: "小3", meanings: ["send", "see off"], onyomi: ["ソウ"], kunyomi: ["おく-る"], examples: ["送る (おくる) to send", "放送 (ほうそう) broadcast"] },
    { kanji: "族", level: "小3", meanings: ["tribe", "family"], onyomi: ["ゾク"], kunyomi: [], examples: ["家族 (かぞく) family", "民族 (みんぞく) ethnic group"] },
    { kanji: "代", level: "小3", meanings: ["substitute", "era", "fee"], onyomi: ["ダイ", "タイ"], kunyomi: ["か-わる", "よ", "しろ"], examples: ["時代 (じだい) era", "代わる (かわる) to substitute"] },
    { kanji: "題", level: "小3", meanings: ["title", "topic", "problem"], onyomi: ["ダイ"], kunyomi: [], examples: ["問題 (もんだい) problem", "題名 (だいめい) title"] },
    { kanji: "待", level: "小3", meanings: ["wait"], onyomi: ["タイ"], kunyomi: ["ま-つ"], examples: ["待つ (まつ) to wait", "待合室 (まちあいしつ) waiting room"] },
    { kanji: "炭", level: "小3", meanings: ["coal", "charcoal"], onyomi: ["タン"], kunyomi: ["すみ"], examples: ["炭 (すみ) charcoal", "石炭 (せきたん) coal"] },
    { kanji: "短", level: "小3", meanings: ["short"], onyomi: ["タン"], kunyomi: ["みじか-い"], examples: ["短い (みじかい) short", "短所 (たんしょ) weak point"] },
    { kanji: "着", level: "小3", meanings: ["arrive", "wear"], onyomi: ["チャク", "ジャク"], kunyomi: ["き-る", "つ-く"], examples: ["着る (きる) to wear", "到着 (とうちゃく) arrival"] },
    { kanji: "注", level: "小3", meanings: ["pour", "focus", "note"], onyomi: ["チュウ"], kunyomi: ["そそ-ぐ"], examples: ["注意 (ちゅうい) attention", "注文 (ちゅうもん) order (food)"] },
    { kanji: "丁", level: "小3", meanings: ["adult", "town block", "polite"], onyomi: ["チョウ", "テイ"], kunyomi: [], examples: ["丁寧 (ていねい) polite/careful", "一丁目 (いっちょうめ) 1st block"] },
    { kanji: "帳", level: "小3", meanings: ["notebook", "register"], onyomi: ["チョウ"], kunyomi: [], examples: ["手帳 (てちょう) notebook", "日記帳 (にっきちょう) diary"] },
    { kanji: "転", level: "小3", meanings: ["roll", "turn", "change"], onyomi: ["テン"], kunyomi: ["ころ-がる", "ころ-ぶ"], examples: ["運転 (うんてん) driving", "転ぶ (ころぶ) to fall down"] },
    { kanji: "度", level: "小3", meanings: ["degree", "times", "occasion"], onyomi: ["ド", "ト", "タク"], kunyomi: ["たび"], examples: ["今度 (こんど) next time", "一度 (いちど) once"] },
    { kanji: "投", level: "小3", meanings: ["throw", "invest"], onyomi: ["トウ"], kunyomi: ["な-げる"], examples: ["投げる (なげる) to throw", "投資 (とうし) investment"] },
    { kanji: "島", level: "小3", meanings: ["island"], onyomi: ["トウ"], kunyomi: ["しま"], examples: ["島 (しま) island", "島国 (しまぐに) island country"] },
    { kanji: "湯", level: "小3", meanings: ["hot water", "hot spring"], onyomi: ["トウ"], kunyomi: ["ゆ"], examples: ["お湯 (おゆ) hot water", "温泉 (おんせん) hot spring"] },
    { kanji: "登", level: "小3", meanings: ["climb", "register"], onyomi: ["トウ", "ト"], kunyomi: ["のぼ-る"], examples: ["登る (のぼる) to climb", "登山 (とざん) mountain climbing"] },
    { kanji: "動", level: "小3", meanings: ["move"], onyomi: ["ドウ"], kunyomi: ["うご-く", "うご-かす"], examples: ["動く (うごく) to move", "運動 (うんどう) exercise"] },
    { kanji: "童", level: "小3", meanings: ["child", "juvenile"], onyomi: ["ドウ"], kunyomi: ["わらべ"], examples: ["童話 (どうわ) fairy tale", "児童 (じどう) child"] },
    { kanji: "農", level: "小3", meanings: ["agriculture", "farming"], onyomi: ["ノウ"], kunyomi: [], examples: ["農業 (のうぎょう) agriculture", "農家 (のうか) farm family"] },
    { kanji: "波", level: "小3", meanings: ["wave"], onyomi: ["ハ"], kunyomi: ["なみ"], examples: ["波 (なみ) wave", "電波 (でんぱ) radio wave"] },
    { kanji: "配", level: "小3", meanings: ["distribute", "worry"], onyomi: ["ハイ"], kunyomi: ["くば-る"], examples: ["配る (くばる) to distribute", "心配 (しんぱい) worry"] },
    { kanji: "反", level: "小3", meanings: ["anti", "return", "counter"], onyomi: ["ハン", "ホン", "タン"], kunyomi: ["そ-る", "そ-らす"], examples: ["反対 (はんたい) opposition", "反省 (はんせい) reflection"] },
    { kanji: "板", level: "小3", meanings: ["board", "plank"], onyomi: ["バン", "ハン"], kunyomi: ["いた"], examples: ["板 (いた) board/plank", "黒板 (こくばん) blackboard"] },
    { kanji: "発", level: "小3", meanings: ["depart", "emit", "start"], onyomi: ["ハツ", "ホツ"], kunyomi: [], examples: ["出発 (しゅっぱつ) departure", "発見 (はっけん) discovery"] },
    { kanji: "負", level: "小3", meanings: ["lose", "carry", "negative"], onyomi: ["フ"], kunyomi: ["ま-ける", "お-う"], examples: ["負ける (まける) to lose", "負担 (ふたん) burden"] },
    { kanji: "品", level: "小3", meanings: ["goods", "item", "quality"], onyomi: ["ヒン", "ホン"], kunyomi: ["しな"], examples: ["品物 (しなもの) goods", "商品 (しょうひん) product"] },
    { kanji: "病", level: "小3", meanings: ["illness", "disease"], onyomi: ["ビョウ", "ヘイ"], kunyomi: ["やまい", "や-む"], examples: ["病気 (びょうき) illness", "病院 (びょういん) hospital"] },
    { kanji: "物", level: "小3", meanings: ["thing", "object"], onyomi: ["ブツ", "モツ"], kunyomi: ["もの"], examples: ["物 (もの) thing", "食べ物 (たべもの) food"] },
    { kanji: "服", level: "小3", meanings: ["clothing", "obey"], onyomi: ["フク"], kunyomi: [], examples: ["服 (ふく) clothes", "洋服 (ようふく) Western clothing"] },
    { kanji: "福", level: "小3", meanings: ["good fortune", "happiness"], onyomi: ["フク"], kunyomi: [], examples: ["幸福 (こうふく) happiness", "福祉 (ふくし) welfare"] },
    { kanji: "部", level: "小3", meanings: ["part", "section", "club"], onyomi: ["ブ", "ホ", "フ"], kunyomi: [], examples: ["部分 (ぶぶん) part/portion", "部活 (ぶかつ) club activity"] },
    { kanji: "放", level: "小3", meanings: ["release", "broadcast"], onyomi: ["ホウ"], kunyomi: ["はな-す", "はな-つ", "ほう-る"], examples: ["放送 (ほうそう) broadcast", "解放 (かいほう) liberation"] },
    { kanji: "方", level: "小3", meanings: ["direction", "person", "way"], onyomi: ["ホウ"], kunyomi: ["かた"], examples: ["方向 (ほうこう) direction", "あの方 (あのかた) that person"] },
    { kanji: "平", level: "小3", meanings: ["flat", "peace", "ordinary"], onyomi: ["ヘイ", "ビョウ"], kunyomi: ["たい-ら", "ひら"], examples: ["平和 (へいわ) peace", "平ら (たいら) flat"] },
    { kanji: "返", level: "小3", meanings: ["return", "reply"], onyomi: ["ヘン"], kunyomi: ["かえ-す", "かえ-る"], examples: ["返す (かえす) to return", "返事 (へんじ) reply"] },
    { kanji: "忘", level: "小3", meanings: ["forget"], onyomi: ["ボウ"], kunyomi: ["わす-れる"], examples: ["忘れる (わすれる) to forget", "忘年会 (ぼうねんかい) year-end party"] },
    { kanji: "問", level: "小3", meanings: ["question", "problem"], onyomi: ["モン"], kunyomi: ["と-う", "と-い"], examples: ["問題 (もんだい) problem", "質問 (しつもん) question"] },
    { kanji: "役", level: "小3", meanings: ["role", "service", "use"], onyomi: ["ヤク", "エキ"], kunyomi: [], examples: ["役に立つ (やくにたつ) to be useful", "役割 (やくわり) role"] },
    { kanji: "薬", level: "小3", meanings: ["medicine", "drug"], onyomi: ["ヤク"], kunyomi: ["くすり"], examples: ["薬 (くすり) medicine", "薬局 (やっきょく) pharmacy"] },
    { kanji: "由", level: "小3", meanings: ["reason", "cause"], onyomi: ["ユ", "ユウ", "ユイ"], kunyomi: ["よし", "よ-る"], examples: ["理由 (りゆう) reason", "自由 (じゆう) freedom"] },
    { kanji: "遊", level: "小3", meanings: ["play", "recreation"], onyomi: ["ユウ", "ユ"], kunyomi: ["あそ-ぶ"], examples: ["遊ぶ (あそぶ) to play", "遊び (あそび) play/fun"] },
    { kanji: "有", level: "小3", meanings: ["exist", "have"], onyomi: ["ユウ", "ウ"], kunyomi: ["あ-る"], examples: ["有名 (ゆうめい) famous", "有る (ある) to have"] },
    { kanji: "予", level: "小3", meanings: ["beforehand", "reserve"], onyomi: ["ヨ"], kunyomi: ["あらかじ-め"], examples: ["予習 (よしゅう) preparation", "予定 (よてい) schedule"] },
    { kanji: "様", level: "小3", meanings: ["appearance", "manner", "Mr./Ms."], onyomi: ["ヨウ"], kunyomi: ["さま"], examples: ["様子 (ようす) situation/manner", "お客様 (おきゃくさま) customer"] },
    { kanji: "洋", level: "小3", meanings: ["ocean", "Western"], onyomi: ["ヨウ"], kunyomi: [], examples: ["洋服 (ようふく) Western clothing", "東洋 (とうよう) the East"] },
    { kanji: "油", level: "小3", meanings: ["oil"], onyomi: ["ユ"], kunyomi: ["あぶら"], examples: ["石油 (せきゆ) petroleum", "油 (あぶら) oil"] },
    { kanji: "落", level: "小3", meanings: ["fall", "drop", "decline"], onyomi: ["ラク"], kunyomi: ["お-ちる", "お-とす"], examples: ["落ちる (おちる) to fall", "落とす (おとす) to drop"] },
    { kanji: "理", level: "小3", meanings: ["reason", "logic"], onyomi: ["リ"], kunyomi: ["ことわ-る"], examples: ["料理 (りょうり) cooking", "理由 (りゆう) reason"] },
    { kanji: "料", level: "小3", meanings: ["fee", "material"], onyomi: ["リョウ"], kunyomi: [], examples: ["料理 (りょうり) cooking", "料金 (りょうきん) fee/charge"] },
    { kanji: "旅", level: "小3", meanings: ["travel", "trip"], onyomi: ["リョ"], kunyomi: ["たび"], examples: ["旅行 (りょこう) travel", "旅 (たび) journey"] },
    { kanji: "流", level: "小3", meanings: ["flow", "style"], onyomi: ["リュウ", "ル"], kunyomi: ["なが-れる", "なが-す"], examples: ["流れる (ながれる) to flow", "流行 (りゅうこう) fashion/trend"] },
    { kanji: "列", level: "小3", meanings: ["row", "line", "rank"], onyomi: ["レツ"], kunyomi: [], examples: ["列 (れつ) row/line", "行列 (ぎょうれつ) queue"] },
    { kanji: "礼", level: "小3", meanings: ["gratitude", "manners", "bow"], onyomi: ["レイ", "ライ"], kunyomi: [], examples: ["礼儀 (れいぎ) etiquette", "失礼 (しつれい) rudeness"] },
    { kanji: "練", level: "小3", meanings: ["practice", "knead"], onyomi: ["レン"], kunyomi: ["ね-る"], examples: ["練習 (れんしゅう) practice", "訓練 (くんれん) training"] },
    { kanji: "路", level: "小3", meanings: ["road", "route"], onyomi: ["ロ", "ル"], kunyomi: ["じ"], examples: ["道路 (どうろ) road", "路線 (ろせん) route/line"] },
    { kanji: "和", level: "小3", meanings: ["harmony", "Japan", "sum"], onyomi: ["ワ", "オ"], kunyomi: ["やわ-らぐ", "なご-む"], examples: ["和食 (わしょく) Japanese food", "平和 (へいわ) peace"] },
    { kanji: "世", level: "小3", meanings: ["world", "generation"], onyomi: ["セイ", "セ"], kunyomi: ["よ"], examples: ["世界 (せかい) world", "世の中 (よのなか) society"] },
    { kanji: "界", level: "小3", meanings: ["world", "boundary"], onyomi: ["カイ"], kunyomi: [], examples: ["世界 (せかい) world", "業界 (ぎょうかい) industry"] },
    { kanji: "階", level: "小3", meanings: ["floor level", "rank"], onyomi: ["カイ"], kunyomi: [], examples: ["一階 (いっかい) first floor", "段階 (だんかい) stage/level"] },
    { kanji: "泳", level: "小3", meanings: ["swim"], onyomi: ["エイ"], kunyomi: ["およ-ぐ"], examples: ["泳ぐ (およぐ) to swim", "水泳 (すいえい) swimming"] },
    { kanji: "整", level: "小3", meanings: ["arrange", "organize"], onyomi: ["セイ"], kunyomi: ["ととの-える", "ととの-う"], examples: ["整理 (せいり) arrangement", "整える (ととのえる) to arrange"] },
    { kanji: "次", level: "小3", meanings: ["next", "order"], onyomi: ["ジ", "シ"], kunyomi: ["つぎ", "つ-ぐ"], examples: ["次 (つぎ) next", "次第 (しだい) circumstance"] },
    { kanji: "勉", level: "小3", meanings: ["study", "endeavor"], onyomi: ["ベン"], kunyomi: [], examples: ["勉強 (べんきょう) study", "勤勉 (きんべん) diligence"] },
    { kanji: "勝", level: "小3", meanings: ["win", "victory"], onyomi: ["ショウ"], kunyomi: ["か-つ", "かち"], examples: ["勝つ (かつ) to win", "勝利 (しょうり) victory"] },
    { kanji: "面", level: "小3", meanings: ["face", "surface", "mask"], onyomi: ["メン", "ベン"], kunyomi: ["おも", "おもて", "つら"], examples: ["面白い (おもしろい) interesting", "場面 (ばめん) scene"] },
    { kanji: "味", level: "小3", meanings: ["taste", "flavor"], onyomi: ["ミ"], kunyomi: ["あじ", "あじ-わう"], examples: ["味 (あじ) taste", "意味 (いみ) meaning"] },
    { kanji: "命", level: "小3", meanings: ["life", "fate", "order"], onyomi: ["メイ", "ミョウ"], kunyomi: ["いのち"], examples: ["命 (いのち) life", "命令 (めいれい) order/command"] },
    { kanji: "緑", level: "小3", meanings: ["green"], onyomi: ["リョク", "ロク"], kunyomi: ["みどり"], examples: ["緑 (みどり) green", "緑茶 (りょくちゃ) green tea"] },
    { kanji: "屋", level: "小3", meanings: ["room", "shop", "roof"], onyomi: ["オク"], kunyomi: ["や"], examples: ["部屋 (へや) room", "八百屋 (やおや) greengrocer"] },
    { kanji: "止", level: "小3", meanings: ["stop"], onyomi: ["シ"], kunyomi: ["と-まる", "と-める", "や-む", "や-める"], examples: ["止まる (とまる) to stop", "止める (とめる) to stop something"] },
    { kanji: "重", level: "小3", meanings: ["heavy", "important"], onyomi: ["ジュウ", "チョウ"], kunyomi: ["おも-い", "かさ-ねる"], examples: ["重い (おもい) heavy", "重要 (じゅうよう) important"] },
    { kanji: "主", level: "小3", meanings: ["master", "main", "lord"], onyomi: ["シュ", "ス"], kunyomi: ["ぬし", "おも-"], examples: ["主人 (しゅじん) husband/master", "主な (おもな) main"] },
    { kanji: "音", level: "小3", meanings: ["sound", "music"], onyomi: ["オン", "イン"], kunyomi: ["おと", "ね"], examples: ["音楽 (おんがく) music", "音 (おと) sound"] },
    { kanji: "府", level: "小3", meanings: ["city", "government"], onyomi: ["フ"], kunyomi: [], examples: ["政府 (せいふ) government", "大阪府 (おおさかふ) Osaka Prefecture"] },
];

// Remove duplicate entries (same kanji)
const seen = new Set();
const KANJI = KANJI_DATA.filter(k => {
    if (seen.has(k.kanji)) return false;
    seen.add(k.kanji);
    return true;
});